// Generated by gencpp from file GNSS_Decoding_py/GNSS_Output.msg
// DO NOT EDIT!


#ifndef GNSS_DECODING_PY_MESSAGE_GNSS_OUTPUT_H
#define GNSS_DECODING_PY_MESSAGE_GNSS_OUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace GNSS_Decoding_py
{
template <class ContainerAllocator>
struct GNSS_Output_
{
  typedef GNSS_Output_<ContainerAllocator> Type;

  GNSS_Output_()
    : header()
    , OutputRecordType(false)
    , RecordLength(false)
    , GPSWeek(0)
    , GPSTime(0)
    , IMUAlignmentStatus(false)
    , GNSSStatus(false)
    , X_E(0.0)
    , Y_N(0.0)
    , Altitude(0.0)
    , VelocityN(0.0)
    , VelocityE(0.0)
    , VelocityDown(0.0)
    , TotalVelocity(0.0)
    , Roll(0.0)
    , Pitch(0.0)
    , Yaw_N(0.0)
    , TrackingAngle(0.0)
    , RollRate(0.0)
    , PitchRate(0.0)
    , YawRate_N(0.0)
    , ax(0.0)
    , ay(0.0)
    , az(0.0)  {
    }
  GNSS_Output_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , OutputRecordType(false)
    , RecordLength(false)
    , GPSWeek(0)
    , GPSTime(0)
    , IMUAlignmentStatus(false)
    , GNSSStatus(false)
    , X_E(0.0)
    , Y_N(0.0)
    , Altitude(0.0)
    , VelocityN(0.0)
    , VelocityE(0.0)
    , VelocityDown(0.0)
    , TotalVelocity(0.0)
    , Roll(0.0)
    , Pitch(0.0)
    , Yaw_N(0.0)
    , TrackingAngle(0.0)
    , RollRate(0.0)
    , PitchRate(0.0)
    , YawRate_N(0.0)
    , ax(0.0)
    , ay(0.0)
    , az(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _OutputRecordType_type;
  _OutputRecordType_type OutputRecordType;

   typedef uint8_t _RecordLength_type;
  _RecordLength_type RecordLength;

   typedef uint16_t _GPSWeek_type;
  _GPSWeek_type GPSWeek;

   typedef uint32_t _GPSTime_type;
  _GPSTime_type GPSTime;

   typedef uint8_t _IMUAlignmentStatus_type;
  _IMUAlignmentStatus_type IMUAlignmentStatus;

   typedef uint8_t _GNSSStatus_type;
  _GNSSStatus_type GNSSStatus;

   typedef float _X_E_type;
  _X_E_type X_E;

   typedef float _Y_N_type;
  _Y_N_type Y_N;

   typedef float _Altitude_type;
  _Altitude_type Altitude;

   typedef float _VelocityN_type;
  _VelocityN_type VelocityN;

   typedef float _VelocityE_type;
  _VelocityE_type VelocityE;

   typedef float _VelocityDown_type;
  _VelocityDown_type VelocityDown;

   typedef float _TotalVelocity_type;
  _TotalVelocity_type TotalVelocity;

   typedef float _Roll_type;
  _Roll_type Roll;

   typedef float _Pitch_type;
  _Pitch_type Pitch;

   typedef float _Yaw_N_type;
  _Yaw_N_type Yaw_N;

   typedef float _TrackingAngle_type;
  _TrackingAngle_type TrackingAngle;

   typedef float _RollRate_type;
  _RollRate_type RollRate;

   typedef float _PitchRate_type;
  _PitchRate_type PitchRate;

   typedef float _YawRate_N_type;
  _YawRate_N_type YawRate_N;

   typedef float _ax_type;
  _ax_type ax;

   typedef float _ay_type;
  _ay_type ay;

   typedef float _az_type;
  _az_type az;





  typedef boost::shared_ptr< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> const> ConstPtr;

}; // struct GNSS_Output_

typedef ::GNSS_Decoding_py::GNSS_Output_<std::allocator<void> > GNSS_Output;

typedef boost::shared_ptr< ::GNSS_Decoding_py::GNSS_Output > GNSS_OutputPtr;
typedef boost::shared_ptr< ::GNSS_Decoding_py::GNSS_Output const> GNSS_OutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator1> & lhs, const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.OutputRecordType == rhs.OutputRecordType &&
    lhs.RecordLength == rhs.RecordLength &&
    lhs.GPSWeek == rhs.GPSWeek &&
    lhs.GPSTime == rhs.GPSTime &&
    lhs.IMUAlignmentStatus == rhs.IMUAlignmentStatus &&
    lhs.GNSSStatus == rhs.GNSSStatus &&
    lhs.X_E == rhs.X_E &&
    lhs.Y_N == rhs.Y_N &&
    lhs.Altitude == rhs.Altitude &&
    lhs.VelocityN == rhs.VelocityN &&
    lhs.VelocityE == rhs.VelocityE &&
    lhs.VelocityDown == rhs.VelocityDown &&
    lhs.TotalVelocity == rhs.TotalVelocity &&
    lhs.Roll == rhs.Roll &&
    lhs.Pitch == rhs.Pitch &&
    lhs.Yaw_N == rhs.Yaw_N &&
    lhs.TrackingAngle == rhs.TrackingAngle &&
    lhs.RollRate == rhs.RollRate &&
    lhs.PitchRate == rhs.PitchRate &&
    lhs.YawRate_N == rhs.YawRate_N &&
    lhs.ax == rhs.ax &&
    lhs.ay == rhs.ay &&
    lhs.az == rhs.az;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator1> & lhs, const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace GNSS_Decoding_py

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a180986276a6872e41703ee50456ad6";
  }

  static const char* value(const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a180986276a6872ULL;
  static const uint64_t static_value2 = 0xe41703ee50456ad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "GNSS_Decoding_py/GNSS_Output";
  }

  static const char* value(const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool OutputRecordType\n"
"bool RecordLength\n"
"uint16 GPSWeek\n"
"uint32 GPSTime\n"
"bool IMUAlignmentStatus\n"
"bool GNSSStatus\n"
"float32 X_E\n"
"float32 Y_N\n"
"float32 Altitude\n"
"float32 VelocityN\n"
"float32 VelocityE\n"
"float32 VelocityDown\n"
"float32 TotalVelocity\n"
"float32 Roll\n"
"float32 Pitch\n"
"float32 Yaw_N\n"
"float32 TrackingAngle\n"
"float32 RollRate\n"
"float32 PitchRate\n"
"float32 YawRate_N\n"
"float32 ax\n"
"float32 ay\n"
"float32 az\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.OutputRecordType);
      stream.next(m.RecordLength);
      stream.next(m.GPSWeek);
      stream.next(m.GPSTime);
      stream.next(m.IMUAlignmentStatus);
      stream.next(m.GNSSStatus);
      stream.next(m.X_E);
      stream.next(m.Y_N);
      stream.next(m.Altitude);
      stream.next(m.VelocityN);
      stream.next(m.VelocityE);
      stream.next(m.VelocityDown);
      stream.next(m.TotalVelocity);
      stream.next(m.Roll);
      stream.next(m.Pitch);
      stream.next(m.Yaw_N);
      stream.next(m.TrackingAngle);
      stream.next(m.RollRate);
      stream.next(m.PitchRate);
      stream.next(m.YawRate_N);
      stream.next(m.ax);
      stream.next(m.ay);
      stream.next(m.az);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GNSS_Output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::GNSS_Decoding_py::GNSS_Output_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "OutputRecordType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.OutputRecordType);
    s << indent << "RecordLength: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RecordLength);
    s << indent << "GPSWeek: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.GPSWeek);
    s << indent << "GPSTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.GPSTime);
    s << indent << "IMUAlignmentStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IMUAlignmentStatus);
    s << indent << "GNSSStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.GNSSStatus);
    s << indent << "X_E: ";
    Printer<float>::stream(s, indent + "  ", v.X_E);
    s << indent << "Y_N: ";
    Printer<float>::stream(s, indent + "  ", v.Y_N);
    s << indent << "Altitude: ";
    Printer<float>::stream(s, indent + "  ", v.Altitude);
    s << indent << "VelocityN: ";
    Printer<float>::stream(s, indent + "  ", v.VelocityN);
    s << indent << "VelocityE: ";
    Printer<float>::stream(s, indent + "  ", v.VelocityE);
    s << indent << "VelocityDown: ";
    Printer<float>::stream(s, indent + "  ", v.VelocityDown);
    s << indent << "TotalVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.TotalVelocity);
    s << indent << "Roll: ";
    Printer<float>::stream(s, indent + "  ", v.Roll);
    s << indent << "Pitch: ";
    Printer<float>::stream(s, indent + "  ", v.Pitch);
    s << indent << "Yaw_N: ";
    Printer<float>::stream(s, indent + "  ", v.Yaw_N);
    s << indent << "TrackingAngle: ";
    Printer<float>::stream(s, indent + "  ", v.TrackingAngle);
    s << indent << "RollRate: ";
    Printer<float>::stream(s, indent + "  ", v.RollRate);
    s << indent << "PitchRate: ";
    Printer<float>::stream(s, indent + "  ", v.PitchRate);
    s << indent << "YawRate_N: ";
    Printer<float>::stream(s, indent + "  ", v.YawRate_N);
    s << indent << "ax: ";
    Printer<float>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<float>::stream(s, indent + "  ", v.ay);
    s << indent << "az: ";
    Printer<float>::stream(s, indent + "  ", v.az);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_DECODING_PY_MESSAGE_GNSS_OUTPUT_H
