// Generated by gencpp from file used_msgs/Lane.msg
// DO NOT EDIT!


#ifndef USED_MSGS_MESSAGE_LANE_H
#define USED_MSGS_MESSAGE_LANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace used_msgs
{
template <class ContainerAllocator>
struct Lane_
{
  typedef Lane_<ContainerAllocator> Type;

  Lane_()
    : lane_idx(0)
    , left_traverse_flag(false)
    , right_traverse_flag(false)
    , lane_width(0.0)  {
    }
  Lane_(const ContainerAllocator& _alloc)
    : lane_idx(0)
    , left_traverse_flag(false)
    , right_traverse_flag(false)
    , lane_width(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _lane_idx_type;
  _lane_idx_type lane_idx;

   typedef uint8_t _left_traverse_flag_type;
  _left_traverse_flag_type left_traverse_flag;

   typedef uint8_t _right_traverse_flag_type;
  _right_traverse_flag_type right_traverse_flag;

   typedef double _lane_width_type;
  _lane_width_type lane_width;





  typedef boost::shared_ptr< ::used_msgs::Lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::used_msgs::Lane_<ContainerAllocator> const> ConstPtr;

}; // struct Lane_

typedef ::used_msgs::Lane_<std::allocator<void> > Lane;

typedef boost::shared_ptr< ::used_msgs::Lane > LanePtr;
typedef boost::shared_ptr< ::used_msgs::Lane const> LaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::used_msgs::Lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::used_msgs::Lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::used_msgs::Lane_<ContainerAllocator1> & lhs, const ::used_msgs::Lane_<ContainerAllocator2> & rhs)
{
  return lhs.lane_idx == rhs.lane_idx &&
    lhs.left_traverse_flag == rhs.left_traverse_flag &&
    lhs.right_traverse_flag == rhs.right_traverse_flag &&
    lhs.lane_width == rhs.lane_width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::used_msgs::Lane_<ContainerAllocator1> & lhs, const ::used_msgs::Lane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace used_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::used_msgs::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::used_msgs::Lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::used_msgs::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::used_msgs::Lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::used_msgs::Lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::used_msgs::Lane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::used_msgs::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ce3889449b1a37c2f794128b57abf80";
  }

  static const char* value(const ::used_msgs::Lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ce3889449b1a37cULL;
  static const uint64_t static_value2 = 0x2f794128b57abf80ULL;
};

template<class ContainerAllocator>
struct DataType< ::used_msgs::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "used_msgs/Lane";
  }

  static const char* value(const ::used_msgs::Lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::used_msgs::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 lane_idx\n"
"bool left_traverse_flag \n"
"bool right_traverse_flag\n"
"float64 lane_width\n"
;
  }

  static const char* value(const ::used_msgs::Lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::used_msgs::Lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lane_idx);
      stream.next(m.left_traverse_flag);
      stream.next(m.right_traverse_flag);
      stream.next(m.lane_width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::used_msgs::Lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::used_msgs::Lane_<ContainerAllocator>& v)
  {
    s << indent << "lane_idx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lane_idx);
    s << indent << "left_traverse_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_traverse_flag);
    s << indent << "right_traverse_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_traverse_flag);
    s << indent << "lane_width: ";
    Printer<double>::stream(s, indent + "  ", v.lane_width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USED_MSGS_MESSAGE_LANE_H
