// Generated by gencpp from file used_msgs/Traffic_light.msg
// DO NOT EDIT!


#ifndef USED_MSGS_MESSAGE_TRAFFIC_LIGHT_H
#define USED_MSGS_MESSAGE_TRAFFIC_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace used_msgs
{
template <class ContainerAllocator>
struct Traffic_light_
{
  typedef Traffic_light_<ContainerAllocator> Type;

  Traffic_light_()
    : header()
    , left_light_status(0)
    , straight_light_status(0)
    , right_light_status(0)  {
    }
  Traffic_light_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_light_status(0)
    , straight_light_status(0)
    , right_light_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _left_light_status_type;
  _left_light_status_type left_light_status;

   typedef uint8_t _straight_light_status_type;
  _straight_light_status_type straight_light_status;

   typedef uint8_t _right_light_status_type;
  _right_light_status_type right_light_status;





  typedef boost::shared_ptr< ::used_msgs::Traffic_light_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::used_msgs::Traffic_light_<ContainerAllocator> const> ConstPtr;

}; // struct Traffic_light_

typedef ::used_msgs::Traffic_light_<std::allocator<void> > Traffic_light;

typedef boost::shared_ptr< ::used_msgs::Traffic_light > Traffic_lightPtr;
typedef boost::shared_ptr< ::used_msgs::Traffic_light const> Traffic_lightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::used_msgs::Traffic_light_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::used_msgs::Traffic_light_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::used_msgs::Traffic_light_<ContainerAllocator1> & lhs, const ::used_msgs::Traffic_light_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_light_status == rhs.left_light_status &&
    lhs.straight_light_status == rhs.straight_light_status &&
    lhs.right_light_status == rhs.right_light_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::used_msgs::Traffic_light_<ContainerAllocator1> & lhs, const ::used_msgs::Traffic_light_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace used_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::used_msgs::Traffic_light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::used_msgs::Traffic_light_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::used_msgs::Traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::used_msgs::Traffic_light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::used_msgs::Traffic_light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::used_msgs::Traffic_light_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::used_msgs::Traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6c7743f4ef479871efcca7fc31ddd3a";
  }

  static const char* value(const ::used_msgs::Traffic_light_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6c7743f4ef47987ULL;
  static const uint64_t static_value2 = 0x1efcca7fc31ddd3aULL;
};

template<class ContainerAllocator>
struct DataType< ::used_msgs::Traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "used_msgs/Traffic_light";
  }

  static const char* value(const ::used_msgs::Traffic_light_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::used_msgs::Traffic_light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 left_light_status\n"
"uint8 straight_light_status\n"
"uint8 right_light_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::used_msgs::Traffic_light_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::used_msgs::Traffic_light_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_light_status);
      stream.next(m.straight_light_status);
      stream.next(m.right_light_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Traffic_light_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::used_msgs::Traffic_light_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::used_msgs::Traffic_light_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_light_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_light_status);
    s << indent << "straight_light_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.straight_light_status);
    s << indent << "right_light_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_light_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USED_MSGS_MESSAGE_TRAFFIC_LIGHT_H
