// Generated by gencpp from file rl_planning/CSP.msg
// DO NOT EDIT!


#ifndef RL_PLANNING_MESSAGE_CSP_H
#define RL_PLANNING_MESSAGE_CSP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rl_planning
{
template <class ContainerAllocator>
struct CSP_
{
  typedef CSP_<ContainerAllocator> Type;

  CSP_()
    : s()
    , nx(0.0)
    , sx_a()
    , sx_b()
    , sx_c()
    , sx_d()
    , sx_y()
    , sy_a()
    , sy_b()
    , sy_c()
    , sy_d()
    , sy_y()
    , sz_a()
    , sz_b()
    , sz_c()
    , sz_d()
    , sz_y()  {
    }
  CSP_(const ContainerAllocator& _alloc)
    : s(_alloc)
    , nx(0.0)
    , sx_a(_alloc)
    , sx_b(_alloc)
    , sx_c(_alloc)
    , sx_d(_alloc)
    , sx_y(_alloc)
    , sy_a(_alloc)
    , sy_b(_alloc)
    , sy_c(_alloc)
    , sy_d(_alloc)
    , sy_y(_alloc)
    , sz_a(_alloc)
    , sz_b(_alloc)
    , sz_c(_alloc)
    , sz_d(_alloc)
    , sz_y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _s_type;
  _s_type s;

   typedef double _nx_type;
  _nx_type nx;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sx_a_type;
  _sx_a_type sx_a;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sx_b_type;
  _sx_b_type sx_b;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sx_c_type;
  _sx_c_type sx_c;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sx_d_type;
  _sx_d_type sx_d;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sx_y_type;
  _sx_y_type sx_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sy_a_type;
  _sy_a_type sy_a;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sy_b_type;
  _sy_b_type sy_b;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sy_c_type;
  _sy_c_type sy_c;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sy_d_type;
  _sy_d_type sy_d;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sy_y_type;
  _sy_y_type sy_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sz_a_type;
  _sz_a_type sz_a;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sz_b_type;
  _sz_b_type sz_b;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sz_c_type;
  _sz_c_type sz_c;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sz_d_type;
  _sz_d_type sz_d;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sz_y_type;
  _sz_y_type sz_y;





  typedef boost::shared_ptr< ::rl_planning::CSP_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_planning::CSP_<ContainerAllocator> const> ConstPtr;

}; // struct CSP_

typedef ::rl_planning::CSP_<std::allocator<void> > CSP;

typedef boost::shared_ptr< ::rl_planning::CSP > CSPPtr;
typedef boost::shared_ptr< ::rl_planning::CSP const> CSPConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_planning::CSP_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_planning::CSP_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_planning::CSP_<ContainerAllocator1> & lhs, const ::rl_planning::CSP_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s &&
    lhs.nx == rhs.nx &&
    lhs.sx_a == rhs.sx_a &&
    lhs.sx_b == rhs.sx_b &&
    lhs.sx_c == rhs.sx_c &&
    lhs.sx_d == rhs.sx_d &&
    lhs.sx_y == rhs.sx_y &&
    lhs.sy_a == rhs.sy_a &&
    lhs.sy_b == rhs.sy_b &&
    lhs.sy_c == rhs.sy_c &&
    lhs.sy_d == rhs.sy_d &&
    lhs.sy_y == rhs.sy_y &&
    lhs.sz_a == rhs.sz_a &&
    lhs.sz_b == rhs.sz_b &&
    lhs.sz_c == rhs.sz_c &&
    lhs.sz_d == rhs.sz_d &&
    lhs.sz_y == rhs.sz_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_planning::CSP_<ContainerAllocator1> & lhs, const ::rl_planning::CSP_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::CSP_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::CSP_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::CSP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::CSP_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::CSP_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::CSP_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_planning::CSP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c6b7b121537c4008bf00bae402fe62f";
  }

  static const char* value(const ::rl_planning::CSP_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c6b7b121537c400ULL;
  static const uint64_t static_value2 = 0x8bf00bae402fe62fULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_planning::CSP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_planning/CSP";
  }

  static const char* value(const ::rl_planning::CSP_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_planning::CSP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] s\n"
"float64 nx\n"
"\n"
"float64[] sx_a\n"
"float64[] sx_b\n"
"float64[] sx_c\n"
"float64[] sx_d\n"
"float64[] sx_y\n"
"\n"
"float64[] sy_a\n"
"float64[] sy_b\n"
"float64[] sy_c\n"
"float64[] sy_d\n"
"float64[] sy_y\n"
"\n"
"float64[] sz_a\n"
"float64[] sz_b\n"
"float64[] sz_c\n"
"float64[] sz_d\n"
"float64[] sz_y\n"
;
  }

  static const char* value(const ::rl_planning::CSP_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_planning::CSP_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.nx);
      stream.next(m.sx_a);
      stream.next(m.sx_b);
      stream.next(m.sx_c);
      stream.next(m.sx_d);
      stream.next(m.sx_y);
      stream.next(m.sy_a);
      stream.next(m.sy_b);
      stream.next(m.sy_c);
      stream.next(m.sy_d);
      stream.next(m.sy_y);
      stream.next(m.sz_a);
      stream.next(m.sz_b);
      stream.next(m.sz_c);
      stream.next(m.sz_d);
      stream.next(m.sz_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CSP_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_planning::CSP_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_planning::CSP_<ContainerAllocator>& v)
  {
    s << indent << "s[]" << std::endl;
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      s << indent << "  s[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s[i]);
    }
    s << indent << "nx: ";
    Printer<double>::stream(s, indent + "  ", v.nx);
    s << indent << "sx_a[]" << std::endl;
    for (size_t i = 0; i < v.sx_a.size(); ++i)
    {
      s << indent << "  sx_a[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sx_a[i]);
    }
    s << indent << "sx_b[]" << std::endl;
    for (size_t i = 0; i < v.sx_b.size(); ++i)
    {
      s << indent << "  sx_b[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sx_b[i]);
    }
    s << indent << "sx_c[]" << std::endl;
    for (size_t i = 0; i < v.sx_c.size(); ++i)
    {
      s << indent << "  sx_c[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sx_c[i]);
    }
    s << indent << "sx_d[]" << std::endl;
    for (size_t i = 0; i < v.sx_d.size(); ++i)
    {
      s << indent << "  sx_d[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sx_d[i]);
    }
    s << indent << "sx_y[]" << std::endl;
    for (size_t i = 0; i < v.sx_y.size(); ++i)
    {
      s << indent << "  sx_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sx_y[i]);
    }
    s << indent << "sy_a[]" << std::endl;
    for (size_t i = 0; i < v.sy_a.size(); ++i)
    {
      s << indent << "  sy_a[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sy_a[i]);
    }
    s << indent << "sy_b[]" << std::endl;
    for (size_t i = 0; i < v.sy_b.size(); ++i)
    {
      s << indent << "  sy_b[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sy_b[i]);
    }
    s << indent << "sy_c[]" << std::endl;
    for (size_t i = 0; i < v.sy_c.size(); ++i)
    {
      s << indent << "  sy_c[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sy_c[i]);
    }
    s << indent << "sy_d[]" << std::endl;
    for (size_t i = 0; i < v.sy_d.size(); ++i)
    {
      s << indent << "  sy_d[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sy_d[i]);
    }
    s << indent << "sy_y[]" << std::endl;
    for (size_t i = 0; i < v.sy_y.size(); ++i)
    {
      s << indent << "  sy_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sy_y[i]);
    }
    s << indent << "sz_a[]" << std::endl;
    for (size_t i = 0; i < v.sz_a.size(); ++i)
    {
      s << indent << "  sz_a[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sz_a[i]);
    }
    s << indent << "sz_b[]" << std::endl;
    for (size_t i = 0; i < v.sz_b.size(); ++i)
    {
      s << indent << "  sz_b[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sz_b[i]);
    }
    s << indent << "sz_c[]" << std::endl;
    for (size_t i = 0; i < v.sz_c.size(); ++i)
    {
      s << indent << "  sz_c[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sz_c[i]);
    }
    s << indent << "sz_d[]" << std::endl;
    for (size_t i = 0; i < v.sz_d.size(); ++i)
    {
      s << indent << "  sz_d[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sz_d[i]);
    }
    s << indent << "sz_y[]" << std::endl;
    for (size_t i = 0; i < v.sz_y.size(); ++i)
    {
      s << indent << "  sz_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sz_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_PLANNING_MESSAGE_CSP_H
