// Generated by gencpp from file rl_planning/RLPlanningPath.msg
// DO NOT EDIT!


#ifndef RL_PLANNING_MESSAGE_RLPLANNINGPATH_H
#define RL_PLANNING_MESSAGE_RLPLANNINGPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rl_planning
{
template <class ContainerAllocator>
struct RLPlanningPath_
{
  typedef RLPlanningPath_<ContainerAllocator> Type;

  RLPlanningPath_()
    : header()
    , fx()
    , fy()
    , v()
    , a()
    , theta()
    , kappa()
    , s()
    , collision_risk(0)
    , SRQ_value(0.0)  {
      fx.assign(0.0);

      fy.assign(0.0);

      v.assign(0.0);

      a.assign(0.0);

      theta.assign(0.0);

      kappa.assign(0.0);

      s.assign(0.0);
  }
  RLPlanningPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fx()
    , fy()
    , v()
    , a()
    , theta()
    , kappa()
    , s()
    , collision_risk(0)
    , SRQ_value(0.0)  {
  (void)_alloc;
      fx.assign(0.0);

      fy.assign(0.0);

      v.assign(0.0);

      a.assign(0.0);

      theta.assign(0.0);

      kappa.assign(0.0);

      s.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 500>  _fx_type;
  _fx_type fx;

   typedef boost::array<double, 500>  _fy_type;
  _fy_type fy;

   typedef boost::array<double, 500>  _v_type;
  _v_type v;

   typedef boost::array<double, 500>  _a_type;
  _a_type a;

   typedef boost::array<double, 500>  _theta_type;
  _theta_type theta;

   typedef boost::array<double, 500>  _kappa_type;
  _kappa_type kappa;

   typedef boost::array<double, 500>  _s_type;
  _s_type s;

   typedef int32_t _collision_risk_type;
  _collision_risk_type collision_risk;

   typedef double _SRQ_value_type;
  _SRQ_value_type SRQ_value;





  typedef boost::shared_ptr< ::rl_planning::RLPlanningPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_planning::RLPlanningPath_<ContainerAllocator> const> ConstPtr;

}; // struct RLPlanningPath_

typedef ::rl_planning::RLPlanningPath_<std::allocator<void> > RLPlanningPath;

typedef boost::shared_ptr< ::rl_planning::RLPlanningPath > RLPlanningPathPtr;
typedef boost::shared_ptr< ::rl_planning::RLPlanningPath const> RLPlanningPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_planning::RLPlanningPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_planning::RLPlanningPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_planning::RLPlanningPath_<ContainerAllocator1> & lhs, const ::rl_planning::RLPlanningPath_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fx == rhs.fx &&
    lhs.fy == rhs.fy &&
    lhs.v == rhs.v &&
    lhs.a == rhs.a &&
    lhs.theta == rhs.theta &&
    lhs.kappa == rhs.kappa &&
    lhs.s == rhs.s &&
    lhs.collision_risk == rhs.collision_risk &&
    lhs.SRQ_value == rhs.SRQ_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_planning::RLPlanningPath_<ContainerAllocator1> & lhs, const ::rl_planning::RLPlanningPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::RLPlanningPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::RLPlanningPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::RLPlanningPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "442a1e70c87c57dd2f625de9cdf24bc4";
  }

  static const char* value(const ::rl_planning::RLPlanningPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x442a1e70c87c57ddULL;
  static const uint64_t static_value2 = 0x2f625de9cdf24bc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_planning/RLPlanningPath";
  }

  static const char* value(const ::rl_planning::RLPlanningPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[500] fx\n"
"float64[500] fy\n"
"float64[500] v\n"
"float64[500] a\n"
"float64[500] theta\n"
"float64[500] kappa\n"
"float64[500] s\n"
"int32 collision_risk\n"
"float64 SRQ_value\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rl_planning::RLPlanningPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fx);
      stream.next(m.fy);
      stream.next(m.v);
      stream.next(m.a);
      stream.next(m.theta);
      stream.next(m.kappa);
      stream.next(m.s);
      stream.next(m.collision_risk);
      stream.next(m.SRQ_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLPlanningPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_planning::RLPlanningPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_planning::RLPlanningPath_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fx[]" << std::endl;
    for (size_t i = 0; i < v.fx.size(); ++i)
    {
      s << indent << "  fx[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.fx[i]);
    }
    s << indent << "fy[]" << std::endl;
    for (size_t i = 0; i < v.fy.size(); ++i)
    {
      s << indent << "  fy[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.fy[i]);
    }
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.v[i]);
    }
    s << indent << "a[]" << std::endl;
    for (size_t i = 0; i < v.a.size(); ++i)
    {
      s << indent << "  a[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.a[i]);
    }
    s << indent << "theta[]" << std::endl;
    for (size_t i = 0; i < v.theta.size(); ++i)
    {
      s << indent << "  theta[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.theta[i]);
    }
    s << indent << "kappa[]" << std::endl;
    for (size_t i = 0; i < v.kappa.size(); ++i)
    {
      s << indent << "  kappa[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kappa[i]);
    }
    s << indent << "s[]" << std::endl;
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      s << indent << "  s[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s[i]);
    }
    s << indent << "collision_risk: ";
    Printer<int32_t>::stream(s, indent + "  ", v.collision_risk);
    s << indent << "SRQ_value: ";
    Printer<double>::stream(s, indent + "  ", v.SRQ_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_PLANNING_MESSAGE_RLPLANNINGPATH_H
