// Generated by gencpp from file rl_planning/VehicleInfoBatch.msg
// DO NOT EDIT!


#ifndef RL_PLANNING_MESSAGE_VEHICLEINFOBATCH_H
#define RL_PLANNING_MESSAGE_VEHICLEINFOBATCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rl_planning/VehicleInfo.h>

namespace rl_planning
{
template <class ContainerAllocator>
struct VehicleInfoBatch_
{
  typedef VehicleInfoBatch_<ContainerAllocator> Type;

  VehicleInfoBatch_()
    : header()
    , vehicle_info_batch()  {
    }
  VehicleInfoBatch_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_info_batch(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rl_planning::VehicleInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rl_planning::VehicleInfo_<ContainerAllocator> >::other >  _vehicle_info_batch_type;
  _vehicle_info_batch_type vehicle_info_batch;





  typedef boost::shared_ptr< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleInfoBatch_

typedef ::rl_planning::VehicleInfoBatch_<std::allocator<void> > VehicleInfoBatch;

typedef boost::shared_ptr< ::rl_planning::VehicleInfoBatch > VehicleInfoBatchPtr;
typedef boost::shared_ptr< ::rl_planning::VehicleInfoBatch const> VehicleInfoBatchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_planning::VehicleInfoBatch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_planning::VehicleInfoBatch_<ContainerAllocator1> & lhs, const ::rl_planning::VehicleInfoBatch_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicle_info_batch == rhs.vehicle_info_batch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_planning::VehicleInfoBatch_<ContainerAllocator1> & lhs, const ::rl_planning::VehicleInfoBatch_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "618ce8216f907511a69e15605df7c3cd";
  }

  static const char* value(const ::rl_planning::VehicleInfoBatch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x618ce8216f907511ULL;
  static const uint64_t static_value2 = 0xa69e15605df7c3cdULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_planning/VehicleInfoBatch";
  }

  static const char* value(const ::rl_planning::VehicleInfoBatch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"VehicleInfo[] vehicle_info_batch\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rl_planning/VehicleInfo\n"
"uint32 id\n"
"string label\n"
"geometry_msgs/PolygonStamped convex_hull\n"
"float64 length\n"
"float64 width\n"
"float64 height\n"
"Point actor_pos\n"
"Point actor_rel_pos\n"
"Vector3D actor_vel\n"
"Vector3D actor_rel_vel\n"
"Vector3D actor_acc\n"
"float64 actor_psi\n"
"float64 actor_speed\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: rl_planning/Point\n"
"float64 x \n"
"float64 y \n"
"float64 z \n"
"\n"
"================================================================================\n"
"MSG: rl_planning/Vector3D\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rl_planning::VehicleInfoBatch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_info_batch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleInfoBatch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_planning::VehicleInfoBatch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_planning::VehicleInfoBatch_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_info_batch[]" << std::endl;
    for (size_t i = 0; i < v.vehicle_info_batch.size(); ++i)
    {
      s << indent << "  vehicle_info_batch[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rl_planning::VehicleInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.vehicle_info_batch[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_PLANNING_MESSAGE_VEHICLEINFOBATCH_H
