// Generated by gencpp from file rl_planning/VehicleInfo.msg
// DO NOT EDIT!


#ifndef RL_PLANNING_MESSAGE_VEHICLEINFO_H
#define RL_PLANNING_MESSAGE_VEHICLEINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>
#include <rl_planning/Point.h>
#include <rl_planning/Point.h>
#include <rl_planning/Vector3D.h>
#include <rl_planning/Vector3D.h>
#include <rl_planning/Vector3D.h>

namespace rl_planning
{
template <class ContainerAllocator>
struct VehicleInfo_
{
  typedef VehicleInfo_<ContainerAllocator> Type;

  VehicleInfo_()
    : id(0)
    , label()
    , convex_hull()
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , actor_pos()
    , actor_rel_pos()
    , actor_vel()
    , actor_rel_vel()
    , actor_acc()
    , actor_psi(0.0)
    , actor_speed(0.0)  {
    }
  VehicleInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , label(_alloc)
    , convex_hull(_alloc)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , actor_pos(_alloc)
    , actor_rel_pos(_alloc)
    , actor_vel(_alloc)
    , actor_rel_vel(_alloc)
    , actor_acc(_alloc)
    , actor_psi(0.0)
    , actor_speed(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _convex_hull_type;
  _convex_hull_type convex_hull;

   typedef double _length_type;
  _length_type length;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;

   typedef  ::rl_planning::Point_<ContainerAllocator>  _actor_pos_type;
  _actor_pos_type actor_pos;

   typedef  ::rl_planning::Point_<ContainerAllocator>  _actor_rel_pos_type;
  _actor_rel_pos_type actor_rel_pos;

   typedef  ::rl_planning::Vector3D_<ContainerAllocator>  _actor_vel_type;
  _actor_vel_type actor_vel;

   typedef  ::rl_planning::Vector3D_<ContainerAllocator>  _actor_rel_vel_type;
  _actor_rel_vel_type actor_rel_vel;

   typedef  ::rl_planning::Vector3D_<ContainerAllocator>  _actor_acc_type;
  _actor_acc_type actor_acc;

   typedef double _actor_psi_type;
  _actor_psi_type actor_psi;

   typedef double _actor_speed_type;
  _actor_speed_type actor_speed;





  typedef boost::shared_ptr< ::rl_planning::VehicleInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_planning::VehicleInfo_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleInfo_

typedef ::rl_planning::VehicleInfo_<std::allocator<void> > VehicleInfo;

typedef boost::shared_ptr< ::rl_planning::VehicleInfo > VehicleInfoPtr;
typedef boost::shared_ptr< ::rl_planning::VehicleInfo const> VehicleInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_planning::VehicleInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_planning::VehicleInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_planning::VehicleInfo_<ContainerAllocator1> & lhs, const ::rl_planning::VehicleInfo_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.label == rhs.label &&
    lhs.convex_hull == rhs.convex_hull &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.actor_pos == rhs.actor_pos &&
    lhs.actor_rel_pos == rhs.actor_rel_pos &&
    lhs.actor_vel == rhs.actor_vel &&
    lhs.actor_rel_vel == rhs.actor_rel_vel &&
    lhs.actor_acc == rhs.actor_acc &&
    lhs.actor_psi == rhs.actor_psi &&
    lhs.actor_speed == rhs.actor_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_planning::VehicleInfo_<ContainerAllocator1> & lhs, const ::rl_planning::VehicleInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::VehicleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_planning::VehicleInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::VehicleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_planning::VehicleInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::VehicleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_planning::VehicleInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_planning::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2080f30d52a247820d94f7875c4574f1";
  }

  static const char* value(const ::rl_planning::VehicleInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2080f30d52a24782ULL;
  static const uint64_t static_value2 = 0x0d94f7875c4574f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_planning::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_planning/VehicleInfo";
  }

  static const char* value(const ::rl_planning::VehicleInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_planning::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"string label\n"
"geometry_msgs/PolygonStamped convex_hull\n"
"float64 length\n"
"float64 width\n"
"float64 height\n"
"Point actor_pos\n"
"Point actor_rel_pos\n"
"Vector3D actor_vel\n"
"Vector3D actor_rel_vel\n"
"Vector3D actor_acc\n"
"float64 actor_psi\n"
"float64 actor_speed\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: rl_planning/Point\n"
"float64 x \n"
"float64 y \n"
"float64 z \n"
"\n"
"================================================================================\n"
"MSG: rl_planning/Vector3D\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rl_planning::VehicleInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_planning::VehicleInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.label);
      stream.next(m.convex_hull);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.actor_pos);
      stream.next(m.actor_rel_pos);
      stream.next(m.actor_vel);
      stream.next(m.actor_rel_vel);
      stream.next(m.actor_acc);
      stream.next(m.actor_psi);
      stream.next(m.actor_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_planning::VehicleInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_planning::VehicleInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "convex_hull: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.convex_hull);
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "actor_pos: ";
    s << std::endl;
    Printer< ::rl_planning::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_pos);
    s << indent << "actor_rel_pos: ";
    s << std::endl;
    Printer< ::rl_planning::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_rel_pos);
    s << indent << "actor_vel: ";
    s << std::endl;
    Printer< ::rl_planning::Vector3D_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_vel);
    s << indent << "actor_rel_vel: ";
    s << std::endl;
    Printer< ::rl_planning::Vector3D_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_rel_vel);
    s << indent << "actor_acc: ";
    s << std::endl;
    Printer< ::rl_planning::Vector3D_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_acc);
    s << indent << "actor_psi: ";
    Printer<double>::stream(s, indent + "  ", v.actor_psi);
    s << indent << "actor_speed: ";
    Printer<double>::stream(s, indent + "  ", v.actor_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_PLANNING_MESSAGE_VEHICLEINFO_H
