(cl:in-package plusgo_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOURCE-VAL
          SOURCE
          EXIST_CONFIDENCE-VAL
          EXIST_CONFIDENCE
          TYPE-VAL
          TYPE
          TYPE_CONFIDENCE-VAL
          TYPE_CONFIDENCE
          TRACK_ID-VAL
          TRACK_ID
          TRACKING_TIME-VAL
          TRACKING_TIME
          MOTION_STATE-VAL
          MOTION_STATE
          ANCHOR-VAL
          ANCHOR
          THETA-VAL
          THETA
          DIRECTION-VAL
          DIRECTION
          DIRECTION_COV-VAL
          DIRECTION_COV
          CENTER-VAL
          CENTER
          CENTER_COV-VAL
          CENTER_COV
          SIZE-VAL
          SIZE
          SIZE_COV-VAL
          SIZE_COV
          IS_ABSOLUTE_POSITION-VAL
          IS_ABSOLUTE_POSITION
          VELOCITY-VAL
          VELOCITY
          VELOCITY_COV-VAL
          VELOCITY_COV
          ACCELERATION-VAL
          ACCELERATION
          ACCELERATION_COV-VAL
          ACCELERATION_COV
          ANGLE_VELOCITY-VAL
          ANGLE_VELOCITY
          ANGLE_VELOCITY_COV-VAL
          ANGLE_VELOCITY_COV
          ANGLE_ACCELERATION-VAL
          ANGLE_ACCELERATION
          ANGLE_ACCELERATION_COV-VAL
          ANGLE_ACCELERATION_COV
          TRAJECTORY-VAL
          TRAJECTORY
          HISTORY_TYPE-VAL
          HISTORY_TYPE
          HISTORY_VELOCITY-VAL
          HISTORY_VELOCITY
          POLYGON-VAL
          POLYGON
          RECT-VAL
          RECT
))