# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from GNSS_Decoding_py/GNSS_Output.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class GNSS_Output(genpy.Message):
  _md5sum = "5a180986276a6872e41703ee50456ad6"
  _type = "GNSS_Decoding_py/GNSS_Output"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
bool OutputRecordType
bool RecordLength
uint16 GPSWeek
uint32 GPSTime
bool IMUAlignmentStatus
bool GNSSStatus
float32 X_E
float32 Y_N
float32 Altitude
float32 VelocityN
float32 VelocityE
float32 VelocityDown
float32 TotalVelocity
float32 Roll
float32 Pitch
float32 Yaw_N
float32 TrackingAngle
float32 RollRate
float32 PitchRate
float32 YawRate_N
float32 ax
float32 ay
float32 az
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','OutputRecordType','RecordLength','GPSWeek','GPSTime','IMUAlignmentStatus','GNSSStatus','X_E','Y_N','Altitude','VelocityN','VelocityE','VelocityDown','TotalVelocity','Roll','Pitch','Yaw_N','TrackingAngle','RollRate','PitchRate','YawRate_N','ax','ay','az']
  _slot_types = ['std_msgs/Header','bool','bool','uint16','uint32','bool','bool','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,OutputRecordType,RecordLength,GPSWeek,GPSTime,IMUAlignmentStatus,GNSSStatus,X_E,Y_N,Altitude,VelocityN,VelocityE,VelocityDown,TotalVelocity,Roll,Pitch,Yaw_N,TrackingAngle,RollRate,PitchRate,YawRate_N,ax,ay,az

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GNSS_Output, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.OutputRecordType is None:
        self.OutputRecordType = False
      if self.RecordLength is None:
        self.RecordLength = False
      if self.GPSWeek is None:
        self.GPSWeek = 0
      if self.GPSTime is None:
        self.GPSTime = 0
      if self.IMUAlignmentStatus is None:
        self.IMUAlignmentStatus = False
      if self.GNSSStatus is None:
        self.GNSSStatus = False
      if self.X_E is None:
        self.X_E = 0.
      if self.Y_N is None:
        self.Y_N = 0.
      if self.Altitude is None:
        self.Altitude = 0.
      if self.VelocityN is None:
        self.VelocityN = 0.
      if self.VelocityE is None:
        self.VelocityE = 0.
      if self.VelocityDown is None:
        self.VelocityDown = 0.
      if self.TotalVelocity is None:
        self.TotalVelocity = 0.
      if self.Roll is None:
        self.Roll = 0.
      if self.Pitch is None:
        self.Pitch = 0.
      if self.Yaw_N is None:
        self.Yaw_N = 0.
      if self.TrackingAngle is None:
        self.TrackingAngle = 0.
      if self.RollRate is None:
        self.RollRate = 0.
      if self.PitchRate is None:
        self.PitchRate = 0.
      if self.YawRate_N is None:
        self.YawRate_N = 0.
      if self.ax is None:
        self.ax = 0.
      if self.ay is None:
        self.ay = 0.
      if self.az is None:
        self.az = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.OutputRecordType = False
      self.RecordLength = False
      self.GPSWeek = 0
      self.GPSTime = 0
      self.IMUAlignmentStatus = False
      self.GNSSStatus = False
      self.X_E = 0.
      self.Y_N = 0.
      self.Altitude = 0.
      self.VelocityN = 0.
      self.VelocityE = 0.
      self.VelocityDown = 0.
      self.TotalVelocity = 0.
      self.Roll = 0.
      self.Pitch = 0.
      self.Yaw_N = 0.
      self.TrackingAngle = 0.
      self.RollRate = 0.
      self.PitchRate = 0.
      self.YawRate_N = 0.
      self.ax = 0.
      self.ay = 0.
      self.az = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2BHI2B17f().pack(_x.OutputRecordType, _x.RecordLength, _x.GPSWeek, _x.GPSTime, _x.IMUAlignmentStatus, _x.GNSSStatus, _x.X_E, _x.Y_N, _x.Altitude, _x.VelocityN, _x.VelocityE, _x.VelocityDown, _x.TotalVelocity, _x.Roll, _x.Pitch, _x.Yaw_N, _x.TrackingAngle, _x.RollRate, _x.PitchRate, _x.YawRate_N, _x.ax, _x.ay, _x.az))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 78
      (_x.OutputRecordType, _x.RecordLength, _x.GPSWeek, _x.GPSTime, _x.IMUAlignmentStatus, _x.GNSSStatus, _x.X_E, _x.Y_N, _x.Altitude, _x.VelocityN, _x.VelocityE, _x.VelocityDown, _x.TotalVelocity, _x.Roll, _x.Pitch, _x.Yaw_N, _x.TrackingAngle, _x.RollRate, _x.PitchRate, _x.YawRate_N, _x.ax, _x.ay, _x.az,) = _get_struct_2BHI2B17f().unpack(str[start:end])
      self.OutputRecordType = bool(self.OutputRecordType)
      self.RecordLength = bool(self.RecordLength)
      self.IMUAlignmentStatus = bool(self.IMUAlignmentStatus)
      self.GNSSStatus = bool(self.GNSSStatus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2BHI2B17f().pack(_x.OutputRecordType, _x.RecordLength, _x.GPSWeek, _x.GPSTime, _x.IMUAlignmentStatus, _x.GNSSStatus, _x.X_E, _x.Y_N, _x.Altitude, _x.VelocityN, _x.VelocityE, _x.VelocityDown, _x.TotalVelocity, _x.Roll, _x.Pitch, _x.Yaw_N, _x.TrackingAngle, _x.RollRate, _x.PitchRate, _x.YawRate_N, _x.ax, _x.ay, _x.az))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 78
      (_x.OutputRecordType, _x.RecordLength, _x.GPSWeek, _x.GPSTime, _x.IMUAlignmentStatus, _x.GNSSStatus, _x.X_E, _x.Y_N, _x.Altitude, _x.VelocityN, _x.VelocityE, _x.VelocityDown, _x.TotalVelocity, _x.Roll, _x.Pitch, _x.Yaw_N, _x.TrackingAngle, _x.RollRate, _x.PitchRate, _x.YawRate_N, _x.ax, _x.ay, _x.az,) = _get_struct_2BHI2B17f().unpack(str[start:end])
      self.OutputRecordType = bool(self.OutputRecordType)
      self.RecordLength = bool(self.RecordLength)
      self.IMUAlignmentStatus = bool(self.IMUAlignmentStatus)
      self.GNSSStatus = bool(self.GNSSStatus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BHI2B17f = None
def _get_struct_2BHI2B17f():
    global _struct_2BHI2B17f
    if _struct_2BHI2B17f is None:
        _struct_2BHI2B17f = struct.Struct("<2BHI2B17f")
    return _struct_2BHI2B17f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
