(cl:in-package rl_planning-msg)
(cl:export '(S-VAL
          S
          NX-VAL
          NX
          SX_A-VAL
          SX_A
          SX_B-VAL
          SX_B
          SX_C-VAL
          SX_C
          SX_D-VAL
          SX_D
          SX_Y-VAL
          SX_Y
          SY_A-VAL
          SY_A
          SY_B-VAL
          SY_B
          SY_C-VAL
          SY_C
          SY_D-VAL
          SY_D
          SY_Y-VAL
          SY_Y
          SZ_A-VAL
          SZ_A
          SZ_B-VAL
          SZ_B
          SZ_C-VAL
          SZ_C
          SZ_D-VAL
          SZ_D
          SZ_Y-VAL
          SZ_Y
))