(cl:in-package GNSS_Decoding_py-msg)
(cl:export '(HEADER-VAL
          HEADER
          OUTPUTRECORDTYPE-VAL
          OUTPUTRECORDTYPE
          RECORDLENGTH-VAL
          RECORDLENGTH
          GPSWEEK-VAL
          GPSWEEK
          GPSTIME-VAL
          GPSTIME
          IMUALIGNMENTSTATUS-VAL
          IMUALIGNMENTSTATUS
          GNSSSTATUS-VAL
          GNSSSTATUS
          X_E-VAL
          X_E
          Y_N-VAL
          Y_N
          ALTITUDE-VAL
          ALTITUDE
          VELOCITYN-VAL
          VELOCITYN
          VELOCITYE-VAL
          VELOCITYE
          VELOCITYDOWN-VAL
          VELOCITYDOWN
          TOTALVELOCITY-VAL
          TOTALVELOCITY
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW_N-VAL
          YAW_N
          TRACKINGANGLE-VAL
          TRACKINGANGLE
          ROLLRATE-VAL
          ROLLRATE
          PITCHRATE-VAL
          PITCHRATE
          YAWRATE_N-VAL
          YAWRATE_N
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
))