// Generated by gencpp from file interface/Global_route.msg
// DO NOT EDIT!


#ifndef INTERFACE_MESSAGE_GLOBAL_ROUTE_H
#define INTERFACE_MESSAGE_GLOBAL_ROUTE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <interface/Route.h>

namespace interface
{
template <class ContainerAllocator>
struct Global_route_
{
  typedef Global_route_<ContainerAllocator> Type;

  Global_route_()
    : header()
    , routes()
    , target_route_id(0)  {
    }
  Global_route_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , routes(_alloc)
    , target_route_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::interface::Route_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::interface::Route_<ContainerAllocator> >::other >  _routes_type;
  _routes_type routes;

   typedef int32_t _target_route_id_type;
  _target_route_id_type target_route_id;





  typedef boost::shared_ptr< ::interface::Global_route_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interface::Global_route_<ContainerAllocator> const> ConstPtr;

}; // struct Global_route_

typedef ::interface::Global_route_<std::allocator<void> > Global_route;

typedef boost::shared_ptr< ::interface::Global_route > Global_routePtr;
typedef boost::shared_ptr< ::interface::Global_route const> Global_routeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interface::Global_route_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interface::Global_route_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interface::Global_route_<ContainerAllocator1> & lhs, const ::interface::Global_route_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.routes == rhs.routes &&
    lhs.target_route_id == rhs.target_route_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interface::Global_route_<ContainerAllocator1> & lhs, const ::interface::Global_route_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::interface::Global_route_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interface::Global_route_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::Global_route_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::Global_route_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::Global_route_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::Global_route_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interface::Global_route_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f592139074c730b00ce6171d3313b807";
  }

  static const char* value(const ::interface::Global_route_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf592139074c730b0ULL;
  static const uint64_t static_value2 = 0x0ce6171d3313b807ULL;
};

template<class ContainerAllocator>
struct DataType< ::interface::Global_route_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interface/Global_route";
  }

  static const char* value(const ::interface::Global_route_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interface::Global_route_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Route[] routes\n"
"int32 target_route_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: interface/Route\n"
"Route_point[] points\n"
"================================================================================\n"
"MSG: interface/Route_point\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::interface::Global_route_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interface::Global_route_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.routes);
      stream.next(m.target_route_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Global_route_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interface::Global_route_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interface::Global_route_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "routes[]" << std::endl;
    for (size_t i = 0; i < v.routes.size(); ++i)
    {
      s << indent << "  routes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::interface::Route_<ContainerAllocator> >::stream(s, indent + "    ", v.routes[i]);
    }
    s << indent << "target_route_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_route_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACE_MESSAGE_GLOBAL_ROUTE_H
