// Generated by gencpp from file interface/Lanes.msg
// DO NOT EDIT!


#ifndef INTERFACE_MESSAGE_LANES_H
#define INTERFACE_MESSAGE_LANES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <interface/Lane.h>

namespace interface
{
template <class ContainerAllocator>
struct Lanes_
{
  typedef Lanes_<ContainerAllocator> Type;

  Lanes_()
    : header()
    , curr_idx(0)
    , target_idxes()
    , lanes()  {
    }
  Lanes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , curr_idx(0)
    , target_idxes(_alloc)
    , lanes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _curr_idx_type;
  _curr_idx_type curr_idx;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _target_idxes_type;
  _target_idxes_type target_idxes;

   typedef std::vector< ::interface::Lane_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::interface::Lane_<ContainerAllocator> >::other >  _lanes_type;
  _lanes_type lanes;





  typedef boost::shared_ptr< ::interface::Lanes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interface::Lanes_<ContainerAllocator> const> ConstPtr;

}; // struct Lanes_

typedef ::interface::Lanes_<std::allocator<void> > Lanes;

typedef boost::shared_ptr< ::interface::Lanes > LanesPtr;
typedef boost::shared_ptr< ::interface::Lanes const> LanesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interface::Lanes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interface::Lanes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interface::Lanes_<ContainerAllocator1> & lhs, const ::interface::Lanes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.curr_idx == rhs.curr_idx &&
    lhs.target_idxes == rhs.target_idxes &&
    lhs.lanes == rhs.lanes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interface::Lanes_<ContainerAllocator1> & lhs, const ::interface::Lanes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::interface::Lanes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interface::Lanes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::Lanes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::Lanes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::Lanes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::Lanes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interface::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d6cd6912b68737ee9f67a1266d243c";
  }

  static const char* value(const ::interface::Lanes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d6cd6912b68737ULL;
  static const uint64_t static_value2 = 0xee9f67a1266d243cULL;
};

template<class ContainerAllocator>
struct DataType< ::interface::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interface/Lanes";
  }

  static const char* value(const ::interface::Lanes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interface::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 curr_idx \n"
"uint8[] target_idxes\n"
"Lane[] lanes\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: interface/Lane\n"
"uint8 lane_idx\n"
"bool left_traverse_flag \n"
"bool right_traverse_flag\n"
"float64 lane_width\n"
;
  }

  static const char* value(const ::interface::Lanes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interface::Lanes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.curr_idx);
      stream.next(m.target_idxes);
      stream.next(m.lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lanes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interface::Lanes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interface::Lanes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "curr_idx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.curr_idx);
    s << indent << "target_idxes[]" << std::endl;
    for (size_t i = 0; i < v.target_idxes.size(); ++i)
    {
      s << indent << "  target_idxes[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.target_idxes[i]);
    }
    s << indent << "lanes[]" << std::endl;
    for (size_t i = 0; i < v.lanes.size(); ++i)
    {
      s << indent << "  lanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::interface::Lane_<ContainerAllocator> >::stream(s, indent + "    ", v.lanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACE_MESSAGE_LANES_H
