// Generated by gencpp from file interface/Route.msg
// DO NOT EDIT!


#ifndef INTERFACE_MESSAGE_ROUTE_H
#define INTERFACE_MESSAGE_ROUTE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <interface/Route_point.h>

namespace interface
{
template <class ContainerAllocator>
struct Route_
{
  typedef Route_<ContainerAllocator> Type;

  Route_()
    : points()  {
    }
  Route_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::interface::Route_point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::interface::Route_point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::interface::Route_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interface::Route_<ContainerAllocator> const> ConstPtr;

}; // struct Route_

typedef ::interface::Route_<std::allocator<void> > Route;

typedef boost::shared_ptr< ::interface::Route > RoutePtr;
typedef boost::shared_ptr< ::interface::Route const> RouteConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interface::Route_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interface::Route_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interface::Route_<ContainerAllocator1> & lhs, const ::interface::Route_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interface::Route_<ContainerAllocator1> & lhs, const ::interface::Route_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::interface::Route_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interface::Route_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::Route_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interface::Route_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::Route_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interface::Route_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interface::Route_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f02263beef99aa03117a577a3eb879d";
  }

  static const char* value(const ::interface::Route_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f02263beef99aa0ULL;
  static const uint64_t static_value2 = 0x3117a577a3eb879dULL;
};

template<class ContainerAllocator>
struct DataType< ::interface::Route_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interface/Route";
  }

  static const char* value(const ::interface::Route_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interface::Route_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Route_point[] points\n"
"================================================================================\n"
"MSG: interface/Route_point\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::interface::Route_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interface::Route_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Route_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interface::Route_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interface::Route_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::interface::Route_point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACE_MESSAGE_ROUTE_H
