// Generated by gencpp from file vehicle_info_msgs/VehicleInfoBatch.msg
// DO NOT EDIT!


#ifndef VEHICLE_INFO_MSGS_MESSAGE_VEHICLEINFOBATCH_H
#define VEHICLE_INFO_MSGS_MESSAGE_VEHICLEINFOBATCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vehicle_info_msgs/VehicleInfo.h>

namespace vehicle_info_msgs
{
template <class ContainerAllocator>
struct VehicleInfoBatch_
{
  typedef VehicleInfoBatch_<ContainerAllocator> Type;

  VehicleInfoBatch_()
    : header()
    , vehicle_info_batch()  {
    }
  VehicleInfoBatch_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_info_batch(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >::other >  _vehicle_info_batch_type;
  _vehicle_info_batch_type vehicle_info_batch;





  typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleInfoBatch_

typedef ::vehicle_info_msgs::VehicleInfoBatch_<std::allocator<void> > VehicleInfoBatch;

typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfoBatch > VehicleInfoBatchPtr;
typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfoBatch const> VehicleInfoBatchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator1> & lhs, const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicle_info_batch == rhs.vehicle_info_batch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator1> & lhs, const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_info_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2a582a234afb798175abdbadd03b573";
  }

  static const char* value(const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2a582a234afb798ULL;
  static const uint64_t static_value2 = 0x175abdbadd03b573ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_info_msgs/VehicleInfoBatch";
  }

  static const char* value(const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"vehicle_info_msgs/VehicleInfo[] vehicle_info_batch\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vehicle_info_msgs/VehicleInfo\n"
"# 单个车辆信息\n"
"uint32 id\n"
"string label\n"
"\n"
"# 新增：原始点集合（一般取目标的凸包点）\n"
"geometry_msgs/Point32[] points\n"
"\n"
"# 新增：凸包（带坐标系和时间戳）\n"
"geometry_msgs/PolygonStamped convex_hull\n"
"\n"
"# 目标高度（m）\n"
"float64 height\n"
"\n"
"# 绝对坐标（全局/地图坐标系）\n"
"geometry_msgs/Point actor_pos\n"
"\n"
"# 相对自车坐标（若无法计算，可与绝对坐标一致或置零）\n"
"geometry_msgs/Point actor_rel_pos\n"
"\n"
"# 速度/相对速度/加速度（m/s, m/s, m/s^2）\n"
"geometry_msgs/Vector3 actor_vel\n"
"geometry_msgs/Vector3 actor_rel_vel\n"
"geometry_msgs/Vector3 actor_acc\n"
"\n"
"# 航向（rad，右手系，建议与 plusgo 的 theta 一致）\n"
"float64 actor_psi\n"
"\n"
"# 速度标量（m/s）\n"
"float64 actor_speed\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_info_batch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleInfoBatch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_info_msgs::VehicleInfoBatch_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_info_batch[]" << std::endl;
    for (size_t i = 0; i < v.vehicle_info_batch.size(); ++i)
    {
      s << indent << "  vehicle_info_batch[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.vehicle_info_batch[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_INFO_MSGS_MESSAGE_VEHICLEINFOBATCH_H
