// Generated by gencpp from file vehicle_info_msgs/VehicleInfo.msg
// DO NOT EDIT!


#ifndef VEHICLE_INFO_MSGS_MESSAGE_VEHICLEINFO_H
#define VEHICLE_INFO_MSGS_MESSAGE_VEHICLEINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>
#include <geometry_msgs/PolygonStamped.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace vehicle_info_msgs
{
template <class ContainerAllocator>
struct VehicleInfo_
{
  typedef VehicleInfo_<ContainerAllocator> Type;

  VehicleInfo_()
    : id(0)
    , label()
    , points()
    , convex_hull()
    , height(0.0)
    , actor_pos()
    , actor_rel_pos()
    , actor_vel()
    , actor_rel_vel()
    , actor_acc()
    , actor_psi(0.0)
    , actor_speed(0.0)  {
    }
  VehicleInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , label(_alloc)
    , points(_alloc)
    , convex_hull(_alloc)
    , height(0.0)
    , actor_pos(_alloc)
    , actor_rel_pos(_alloc)
    , actor_vel(_alloc)
    , actor_rel_vel(_alloc)
    , actor_acc(_alloc)
    , actor_psi(0.0)
    , actor_speed(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _convex_hull_type;
  _convex_hull_type convex_hull;

   typedef double _height_type;
  _height_type height;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _actor_pos_type;
  _actor_pos_type actor_pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _actor_rel_pos_type;
  _actor_rel_pos_type actor_rel_pos;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _actor_vel_type;
  _actor_vel_type actor_vel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _actor_rel_vel_type;
  _actor_rel_vel_type actor_rel_vel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _actor_acc_type;
  _actor_acc_type actor_acc;

   typedef double _actor_psi_type;
  _actor_psi_type actor_psi;

   typedef double _actor_speed_type;
  _actor_speed_type actor_speed;





  typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleInfo_

typedef ::vehicle_info_msgs::VehicleInfo_<std::allocator<void> > VehicleInfo;

typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfo > VehicleInfoPtr;
typedef boost::shared_ptr< ::vehicle_info_msgs::VehicleInfo const> VehicleInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator1> & lhs, const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.label == rhs.label &&
    lhs.points == rhs.points &&
    lhs.convex_hull == rhs.convex_hull &&
    lhs.height == rhs.height &&
    lhs.actor_pos == rhs.actor_pos &&
    lhs.actor_rel_pos == rhs.actor_rel_pos &&
    lhs.actor_vel == rhs.actor_vel &&
    lhs.actor_rel_vel == rhs.actor_rel_vel &&
    lhs.actor_acc == rhs.actor_acc &&
    lhs.actor_psi == rhs.actor_psi &&
    lhs.actor_speed == rhs.actor_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator1> & lhs, const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_info_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ca1327c8a619c30ee2b344f65cb183c";
  }

  static const char* value(const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ca1327c8a619c30ULL;
  static const uint64_t static_value2 = 0xee2b344f65cb183cULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_info_msgs/VehicleInfo";
  }

  static const char* value(const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 单个车辆信息\n"
"uint32 id\n"
"string label\n"
"\n"
"# 新增：原始点集合（一般取目标的凸包点）\n"
"geometry_msgs/Point32[] points\n"
"\n"
"# 新增：凸包（带坐标系和时间戳）\n"
"geometry_msgs/PolygonStamped convex_hull\n"
"\n"
"# 目标高度（m）\n"
"float64 height\n"
"\n"
"# 绝对坐标（全局/地图坐标系）\n"
"geometry_msgs/Point actor_pos\n"
"\n"
"# 相对自车坐标（若无法计算，可与绝对坐标一致或置零）\n"
"geometry_msgs/Point actor_rel_pos\n"
"\n"
"# 速度/相对速度/加速度（m/s, m/s, m/s^2）\n"
"geometry_msgs/Vector3 actor_vel\n"
"geometry_msgs/Vector3 actor_rel_vel\n"
"geometry_msgs/Vector3 actor_acc\n"
"\n"
"# 航向（rad，右手系，建议与 plusgo 的 theta 一致）\n"
"float64 actor_psi\n"
"\n"
"# 速度标量（m/s）\n"
"float64 actor_speed\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.label);
      stream.next(m.points);
      stream.next(m.convex_hull);
      stream.next(m.height);
      stream.next(m.actor_pos);
      stream.next(m.actor_rel_pos);
      stream.next(m.actor_vel);
      stream.next(m.actor_rel_vel);
      stream.next(m.actor_acc);
      stream.next(m.actor_psi);
      stream.next(m.actor_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_info_msgs::VehicleInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "convex_hull: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.convex_hull);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "actor_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_pos);
    s << indent << "actor_rel_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_rel_pos);
    s << indent << "actor_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_vel);
    s << indent << "actor_rel_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_rel_vel);
    s << indent << "actor_acc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.actor_acc);
    s << indent << "actor_psi: ";
    Printer<double>::stream(s, indent + "  ", v.actor_psi);
    s << indent << "actor_speed: ";
    Printer<double>::stream(s, indent + "  ", v.actor_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_INFO_MSGS_MESSAGE_VEHICLEINFO_H
