# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from geely_location_msgs/Geely_Location.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Geely_Location(genpy.Message):
  _md5sum = "87793f2358c4810e566e37606b1cc817"
  _type = "geely_location_msgs/Geely_Location"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Geely_Location.msg
# /localization/global_fusion/Location/tju 对应的消息类型

# 时间戳
float64 time

# 标准 ROS 头
std_msgs/Header header

# 原始经纬高
# 约定：x=lon, y=lat, z=height（仅占位，不影响UTM使用）
geometry_msgs/Point position

# 姿态（弧度）
float64 pitch
float64 roll
float64 heading

# ENU 速度/加速度/角速度（单位：m/s, m/s^2, rad/s）
geometry_msgs/Vector3 linear_velocity
geometry_msgs/Vector3 linear_acceleration
geometry_msgs/Vector3 angular_velocity

# 状态标志
int32 rtk_flag
int32 odom_type
int32 auxiliary_type
int32 location_valid_flag

# 原点信息
float64 origin_lat
float64 origin_lon

# UTM 位置（m）：x=East, y=North, z=Up
geometry_msgs/Point utm_position

# 原点切换标记与下一帧UTM
int32 change_origin_flag
geometry_msgs/Point utm_position_next

# 各类标准差（Vector3）
geometry_msgs/Vector3 position_std_dev
geometry_msgs/Vector3 orientation_std_dev
geometry_msgs/Vector3 linear_velocity_std_dev
geometry_msgs/Vector3 linear_acceleration_std_dev
geometry_msgs/Vector3 angular_velocity_std_dev

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['time','header','position','pitch','roll','heading','linear_velocity','linear_acceleration','angular_velocity','rtk_flag','odom_type','auxiliary_type','location_valid_flag','origin_lat','origin_lon','utm_position','change_origin_flag','utm_position_next','position_std_dev','orientation_std_dev','linear_velocity_std_dev','linear_acceleration_std_dev','angular_velocity_std_dev']
  _slot_types = ['float64','std_msgs/Header','geometry_msgs/Point','float64','float64','float64','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','int32','int32','int32','int32','float64','float64','geometry_msgs/Point','int32','geometry_msgs/Point','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,header,position,pitch,roll,heading,linear_velocity,linear_acceleration,angular_velocity,rtk_flag,odom_type,auxiliary_type,location_valid_flag,origin_lat,origin_lon,utm_position,change_origin_flag,utm_position_next,position_std_dev,orientation_std_dev,linear_velocity_std_dev,linear_acceleration_std_dev,angular_velocity_std_dev

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Geely_Location, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.pitch is None:
        self.pitch = 0.
      if self.roll is None:
        self.roll = 0.
      if self.heading is None:
        self.heading = 0.
      if self.linear_velocity is None:
        self.linear_velocity = geometry_msgs.msg.Vector3()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      if self.rtk_flag is None:
        self.rtk_flag = 0
      if self.odom_type is None:
        self.odom_type = 0
      if self.auxiliary_type is None:
        self.auxiliary_type = 0
      if self.location_valid_flag is None:
        self.location_valid_flag = 0
      if self.origin_lat is None:
        self.origin_lat = 0.
      if self.origin_lon is None:
        self.origin_lon = 0.
      if self.utm_position is None:
        self.utm_position = geometry_msgs.msg.Point()
      if self.change_origin_flag is None:
        self.change_origin_flag = 0
      if self.utm_position_next is None:
        self.utm_position_next = geometry_msgs.msg.Point()
      if self.position_std_dev is None:
        self.position_std_dev = geometry_msgs.msg.Vector3()
      if self.orientation_std_dev is None:
        self.orientation_std_dev = geometry_msgs.msg.Vector3()
      if self.linear_velocity_std_dev is None:
        self.linear_velocity_std_dev = geometry_msgs.msg.Vector3()
      if self.linear_acceleration_std_dev is None:
        self.linear_acceleration_std_dev = geometry_msgs.msg.Vector3()
      if self.angular_velocity_std_dev is None:
        self.angular_velocity_std_dev = geometry_msgs.msg.Vector3()
    else:
      self.time = 0.
      self.header = std_msgs.msg.Header()
      self.position = geometry_msgs.msg.Point()
      self.pitch = 0.
      self.roll = 0.
      self.heading = 0.
      self.linear_velocity = geometry_msgs.msg.Vector3()
      self.linear_acceleration = geometry_msgs.msg.Vector3()
      self.angular_velocity = geometry_msgs.msg.Vector3()
      self.rtk_flag = 0
      self.odom_type = 0
      self.auxiliary_type = 0
      self.location_valid_flag = 0
      self.origin_lat = 0.
      self.origin_lon = 0.
      self.utm_position = geometry_msgs.msg.Point()
      self.change_origin_flag = 0
      self.utm_position_next = geometry_msgs.msg.Point()
      self.position_std_dev = geometry_msgs.msg.Vector3()
      self.orientation_std_dev = geometry_msgs.msg.Vector3()
      self.linear_velocity_std_dev = geometry_msgs.msg.Vector3()
      self.linear_acceleration_std_dev = geometry_msgs.msg.Vector3()
      self.angular_velocity_std_dev = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d3I().pack(_x.time, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15d4i5di18d().pack(_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.rtk_flag, _x.odom_type, _x.auxiliary_type, _x.location_valid_flag, _x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.change_origin_flag, _x.utm_position_next.x, _x.utm_position_next.y, _x.utm_position_next.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.linear_velocity is None:
        self.linear_velocity = geometry_msgs.msg.Vector3()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      if self.utm_position is None:
        self.utm_position = geometry_msgs.msg.Point()
      if self.utm_position_next is None:
        self.utm_position_next = geometry_msgs.msg.Point()
      if self.position_std_dev is None:
        self.position_std_dev = geometry_msgs.msg.Vector3()
      if self.orientation_std_dev is None:
        self.orientation_std_dev = geometry_msgs.msg.Vector3()
      if self.linear_velocity_std_dev is None:
        self.linear_velocity_std_dev = geometry_msgs.msg.Vector3()
      if self.linear_acceleration_std_dev is None:
        self.linear_acceleration_std_dev = geometry_msgs.msg.Vector3()
      if self.angular_velocity_std_dev is None:
        self.angular_velocity_std_dev = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.time, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 324
      (_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.rtk_flag, _x.odom_type, _x.auxiliary_type, _x.location_valid_flag, _x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.change_origin_flag, _x.utm_position_next.x, _x.utm_position_next.y, _x.utm_position_next.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z,) = _get_struct_15d4i5di18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d3I().pack(_x.time, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15d4i5di18d().pack(_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.rtk_flag, _x.odom_type, _x.auxiliary_type, _x.location_valid_flag, _x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.change_origin_flag, _x.utm_position_next.x, _x.utm_position_next.y, _x.utm_position_next.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.linear_velocity is None:
        self.linear_velocity = geometry_msgs.msg.Vector3()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      if self.utm_position is None:
        self.utm_position = geometry_msgs.msg.Point()
      if self.utm_position_next is None:
        self.utm_position_next = geometry_msgs.msg.Point()
      if self.position_std_dev is None:
        self.position_std_dev = geometry_msgs.msg.Vector3()
      if self.orientation_std_dev is None:
        self.orientation_std_dev = geometry_msgs.msg.Vector3()
      if self.linear_velocity_std_dev is None:
        self.linear_velocity_std_dev = geometry_msgs.msg.Vector3()
      if self.linear_acceleration_std_dev is None:
        self.linear_acceleration_std_dev = geometry_msgs.msg.Vector3()
      if self.angular_velocity_std_dev is None:
        self.angular_velocity_std_dev = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.time, _x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 324
      (_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.rtk_flag, _x.odom_type, _x.auxiliary_type, _x.location_valid_flag, _x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.change_origin_flag, _x.utm_position_next.x, _x.utm_position_next.y, _x.utm_position_next.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z,) = _get_struct_15d4i5di18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15d4i5di18d = None
def _get_struct_15d4i5di18d():
    global _struct_15d4i5di18d
    if _struct_15d4i5di18d is None:
        _struct_15d4i5di18d = struct.Struct("<15d4i5di18d")
    return _struct_15d4i5di18d
_struct_d3I = None
def _get_struct_d3I():
    global _struct_d3I
    if _struct_d3I is None:
        _struct_d3I = struct.Struct("<d3I")
    return _struct_d3I
