// Generated by gencpp from file plusgo_msgs/ImageRect.msg
// DO NOT EDIT!


#ifndef PLUSGO_MSGS_MESSAGE_IMAGERECT_H
#define PLUSGO_MSGS_MESSAGE_IMAGERECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plusgo_msgs
{
template <class ContainerAllocator>
struct ImageRect_
{
  typedef ImageRect_<ContainerAllocator> Type;

  ImageRect_()
    : image_frame()
    , x(0)
    , y(0)
    , x_(0)
    , y_(0)
    , width(0)
    , height(0)
    , angle(0.0)  {
    }
  ImageRect_(const ContainerAllocator& _alloc)
    : image_frame(_alloc)
    , x(0)
    , y(0)
    , x_(0)
    , y_(0)
    , width(0)
    , height(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_frame_type;
  _image_frame_type image_frame;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _x__type;
  _x__type x_;

   typedef int32_t _y__type;
  _y__type y_;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::plusgo_msgs::ImageRect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plusgo_msgs::ImageRect_<ContainerAllocator> const> ConstPtr;

}; // struct ImageRect_

typedef ::plusgo_msgs::ImageRect_<std::allocator<void> > ImageRect;

typedef boost::shared_ptr< ::plusgo_msgs::ImageRect > ImageRectPtr;
typedef boost::shared_ptr< ::plusgo_msgs::ImageRect const> ImageRectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plusgo_msgs::ImageRect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plusgo_msgs::ImageRect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plusgo_msgs::ImageRect_<ContainerAllocator1> & lhs, const ::plusgo_msgs::ImageRect_<ContainerAllocator2> & rhs)
{
  return lhs.image_frame == rhs.image_frame &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.x_ == rhs.x_ &&
    lhs.y_ == rhs.y_ &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plusgo_msgs::ImageRect_<ContainerAllocator1> & lhs, const ::plusgo_msgs::ImageRect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plusgo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::ImageRect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::ImageRect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::ImageRect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3aed56e31464fbf1a8c8b90d989739bc";
  }

  static const char* value(const ::plusgo_msgs::ImageRect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3aed56e31464fbf1ULL;
  static const uint64_t static_value2 = 0xa8c8b90d989739bcULL;
};

template<class ContainerAllocator>
struct DataType< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plusgo_msgs/ImageRect";
  }

  static const char* value(const ::plusgo_msgs::ImageRect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  image_frame\n"
"int32   x\n"
"int32   y\n"
"int32   x_\n"
"int32   y_\n"
"int32   width\n"
"int32   height\n"
"float32 angle\n"
;
  }

  static const char* value(const ::plusgo_msgs::ImageRect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_frame);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.x_);
      stream.next(m.y_);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageRect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plusgo_msgs::ImageRect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plusgo_msgs::ImageRect_<ContainerAllocator>& v)
  {
    s << indent << "image_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_frame);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "x_: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_);
    s << indent << "y_: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUSGO_MSGS_MESSAGE_IMAGERECT_H
