// Generated by gencpp from file plusgo_msgs/Object.msg
// DO NOT EDIT!


#ifndef PLUSGO_MSGS_MESSAGE_OBJECT_H
#define PLUSGO_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Vector3.h>
#include <plusgo_msgs/Polygon.h>
#include <plusgo_msgs/ImageRect.h>

namespace plusgo_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : header()
    , source(0)
    , exist_confidence(0.0)
    , type(0)
    , type_confidence(0.0)
    , track_id(0)
    , tracking_time(0.0)
    , motion_state(0)
    , anchor()
    , theta(0.0)
    , direction()
    , direction_cov()
    , center()
    , center_cov()
    , size()
    , size_cov()
    , is_absolute_position(false)
    , velocity()
    , velocity_cov()
    , acceleration()
    , acceleration_cov()
    , angle_velocity(0.0)
    , angle_velocity_cov(0.0)
    , angle_acceleration(0.0)
    , angle_acceleration_cov(0.0)
    , trajectory()
    , history_type()
    , history_velocity()
    , polygon()
    , rect()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source(0)
    , exist_confidence(0.0)
    , type(0)
    , type_confidence(0.0)
    , track_id(0)
    , tracking_time(0.0)
    , motion_state(0)
    , anchor(_alloc)
    , theta(0.0)
    , direction(_alloc)
    , direction_cov(_alloc)
    , center(_alloc)
    , center_cov(_alloc)
    , size(_alloc)
    , size_cov(_alloc)
    , is_absolute_position(false)
    , velocity(_alloc)
    , velocity_cov(_alloc)
    , acceleration(_alloc)
    , acceleration_cov(_alloc)
    , angle_velocity(0.0)
    , angle_velocity_cov(0.0)
    , angle_acceleration(0.0)
    , angle_acceleration_cov(0.0)
    , trajectory(_alloc)
    , history_type(_alloc)
    , history_velocity(_alloc)
    , polygon(_alloc)
    , rect(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _source_type;
  _source_type source;

   typedef float _exist_confidence_type;
  _exist_confidence_type exist_confidence;

   typedef int64_t _type_type;
  _type_type type;

   typedef float _type_confidence_type;
  _type_confidence_type type_confidence;

   typedef int64_t _track_id_type;
  _track_id_type track_id;

   typedef float _tracking_time_type;
  _tracking_time_type tracking_time;

   typedef int64_t _motion_state_type;
  _motion_state_type motion_state;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _anchor_type;
  _anchor_type anchor;

   typedef float _theta_type;
  _theta_type theta;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _direction_type;
  _direction_type direction;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _direction_cov_type;
  _direction_cov_type direction_cov;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _center_cov_type;
  _center_cov_type center_cov;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_cov_type;
  _size_cov_type size_cov;

   typedef uint8_t _is_absolute_position_type;
  _is_absolute_position_type is_absolute_position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_cov_type;
  _velocity_cov_type velocity_cov;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_cov_type;
  _acceleration_cov_type acceleration_cov;

   typedef float _angle_velocity_type;
  _angle_velocity_type angle_velocity;

   typedef float _angle_velocity_cov_type;
  _angle_velocity_cov_type angle_velocity_cov;

   typedef float _angle_acceleration_type;
  _angle_acceleration_type angle_acceleration;

   typedef float _angle_acceleration_cov_type;
  _angle_acceleration_cov_type angle_acceleration_cov;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _trajectory_type;
  _trajectory_type trajectory;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _history_type_type;
  _history_type_type history_type;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _history_velocity_type;
  _history_velocity_type history_velocity;

   typedef  ::plusgo_msgs::Polygon_<ContainerAllocator>  _polygon_type;
  _polygon_type polygon;

   typedef  ::plusgo_msgs::ImageRect_<ContainerAllocator>  _rect_type;
  _rect_type rect;





  typedef boost::shared_ptr< ::plusgo_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plusgo_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::plusgo_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::plusgo_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::plusgo_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plusgo_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plusgo_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plusgo_msgs::Object_<ContainerAllocator1> & lhs, const ::plusgo_msgs::Object_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source == rhs.source &&
    lhs.exist_confidence == rhs.exist_confidence &&
    lhs.type == rhs.type &&
    lhs.type_confidence == rhs.type_confidence &&
    lhs.track_id == rhs.track_id &&
    lhs.tracking_time == rhs.tracking_time &&
    lhs.motion_state == rhs.motion_state &&
    lhs.anchor == rhs.anchor &&
    lhs.theta == rhs.theta &&
    lhs.direction == rhs.direction &&
    lhs.direction_cov == rhs.direction_cov &&
    lhs.center == rhs.center &&
    lhs.center_cov == rhs.center_cov &&
    lhs.size == rhs.size &&
    lhs.size_cov == rhs.size_cov &&
    lhs.is_absolute_position == rhs.is_absolute_position &&
    lhs.velocity == rhs.velocity &&
    lhs.velocity_cov == rhs.velocity_cov &&
    lhs.acceleration == rhs.acceleration &&
    lhs.acceleration_cov == rhs.acceleration_cov &&
    lhs.angle_velocity == rhs.angle_velocity &&
    lhs.angle_velocity_cov == rhs.angle_velocity_cov &&
    lhs.angle_acceleration == rhs.angle_acceleration &&
    lhs.angle_acceleration_cov == rhs.angle_acceleration_cov &&
    lhs.trajectory == rhs.trajectory &&
    lhs.history_type == rhs.history_type &&
    lhs.history_velocity == rhs.history_velocity &&
    lhs.polygon == rhs.polygon &&
    lhs.rect == rhs.rect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plusgo_msgs::Object_<ContainerAllocator1> & lhs, const ::plusgo_msgs::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plusgo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plusgo_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "391c844aee60900a62ef240fbbd6467d";
  }

  static const char* value(const ::plusgo_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x391c844aee60900aULL;
  static const uint64_t static_value2 = 0x62ef240fbbd6467dULL;
};

template<class ContainerAllocator>
struct DataType< ::plusgo_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plusgo_msgs/Object";
  }

  static const char* value(const ::plusgo_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plusgo_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8  source\n"
"float32 exist_confidence\n"
"\n"
"# \"UNKNOWN\",\"CONE\",\"PED\",\"BIC\",\"CAR\",\"TRUCK_BUS\",\"ULTRA_VEHICLE\"\n"
"int64  type\n"
"float32 type_confidence\n"
"int64  track_id\n"
"float32 tracking_time\n"
"\n"
"int64  motion_state\n"
"\n"
"geometry_msgs/Point32 anchor\n"
"\n"
"# the yaw angle, theta = 0.0 <=> direction = (1, 0, 0)\n"
"float32 theta\n"
"\n"
"# the main direction is the bbox length orientation\n"
"geometry_msgs/Vector3 direction\n"
"geometry_msgs/Vector3 direction_cov\n"
"geometry_msgs/Point32  center\n"
"geometry_msgs/Point32  center_cov\n"
"\n"
"# size of the oriented boundingbox, length is the size in the main direction\n"
"geometry_msgs/Vector3 size\n"
"geometry_msgs/Vector3 size_cov\n"
"\n"
"bool is_absolute_position\n"
"\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 velocity_cov\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 acceleration_cov\n"
"\n"
"float32 angle_velocity\n"
"float32 angle_velocity_cov\n"
"float32 angle_acceleration\n"
"float32 angle_acceleration_cov\n"
"\n"
"geometry_msgs/Point32[]  trajectory\n"
"geometry_msgs/Point32[]  history_type\n"
"geometry_msgs/Vector3[]  history_velocity\n"
"\n"
"Polygon    polygon\n"
"ImageRect  rect\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: plusgo_msgs/Polygon\n"
"float32 min_height\n"
"float32 max_height\n"
"geometry_msgs/Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: plusgo_msgs/ImageRect\n"
"string  image_frame\n"
"int32   x\n"
"int32   y\n"
"int32   x_\n"
"int32   y_\n"
"int32   width\n"
"int32   height\n"
"float32 angle\n"
;
  }

  static const char* value(const ::plusgo_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plusgo_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source);
      stream.next(m.exist_confidence);
      stream.next(m.type);
      stream.next(m.type_confidence);
      stream.next(m.track_id);
      stream.next(m.tracking_time);
      stream.next(m.motion_state);
      stream.next(m.anchor);
      stream.next(m.theta);
      stream.next(m.direction);
      stream.next(m.direction_cov);
      stream.next(m.center);
      stream.next(m.center_cov);
      stream.next(m.size);
      stream.next(m.size_cov);
      stream.next(m.is_absolute_position);
      stream.next(m.velocity);
      stream.next(m.velocity_cov);
      stream.next(m.acceleration);
      stream.next(m.acceleration_cov);
      stream.next(m.angle_velocity);
      stream.next(m.angle_velocity_cov);
      stream.next(m.angle_acceleration);
      stream.next(m.angle_acceleration_cov);
      stream.next(m.trajectory);
      stream.next(m.history_type);
      stream.next(m.history_velocity);
      stream.next(m.polygon);
      stream.next(m.rect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plusgo_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plusgo_msgs::Object_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    s << indent << "exist_confidence: ";
    Printer<float>::stream(s, indent + "  ", v.exist_confidence);
    s << indent << "type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.type);
    s << indent << "type_confidence: ";
    Printer<float>::stream(s, indent + "  ", v.type_confidence);
    s << indent << "track_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.track_id);
    s << indent << "tracking_time: ";
    Printer<float>::stream(s, indent + "  ", v.tracking_time);
    s << indent << "motion_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.motion_state);
    s << indent << "anchor: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.anchor);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
    s << indent << "direction_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.direction_cov);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "center_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.center_cov);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "size_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size_cov);
    s << indent << "is_absolute_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_absolute_position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "velocity_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_cov);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "acceleration_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration_cov);
    s << indent << "angle_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.angle_velocity);
    s << indent << "angle_velocity_cov: ";
    Printer<float>::stream(s, indent + "  ", v.angle_velocity_cov);
    s << indent << "angle_acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.angle_acceleration);
    s << indent << "angle_acceleration_cov: ";
    Printer<float>::stream(s, indent + "  ", v.angle_acceleration_cov);
    s << indent << "trajectory[]" << std::endl;
    for (size_t i = 0; i < v.trajectory.size(); ++i)
    {
      s << indent << "  trajectory[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectory[i]);
    }
    s << indent << "history_type[]" << std::endl;
    for (size_t i = 0; i < v.history_type.size(); ++i)
    {
      s << indent << "  history_type[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.history_type[i]);
    }
    s << indent << "history_velocity[]" << std::endl;
    for (size_t i = 0; i < v.history_velocity.size(); ++i)
    {
      s << indent << "  history_velocity[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.history_velocity[i]);
    }
    s << indent << "polygon: ";
    s << std::endl;
    Printer< ::plusgo_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.polygon);
    s << indent << "rect: ";
    s << std::endl;
    Printer< ::plusgo_msgs::ImageRect_<ContainerAllocator> >::stream(s, indent + "  ", v.rect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUSGO_MSGS_MESSAGE_OBJECT_H
