// Generated by gencpp from file plusgo_msgs/Objects.msg
// DO NOT EDIT!


#ifndef PLUSGO_MSGS_MESSAGE_OBJECTS_H
#define PLUSGO_MSGS_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <plusgo_msgs/Object.h>

namespace plusgo_msgs
{
template <class ContainerAllocator>
struct Objects_
{
  typedef Objects_<ContainerAllocator> Type;

  Objects_()
    : header()
    , objects()  {
    }
  Objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::plusgo_msgs::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::plusgo_msgs::Object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::plusgo_msgs::Objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plusgo_msgs::Objects_<ContainerAllocator> const> ConstPtr;

}; // struct Objects_

typedef ::plusgo_msgs::Objects_<std::allocator<void> > Objects;

typedef boost::shared_ptr< ::plusgo_msgs::Objects > ObjectsPtr;
typedef boost::shared_ptr< ::plusgo_msgs::Objects const> ObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plusgo_msgs::Objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plusgo_msgs::Objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plusgo_msgs::Objects_<ContainerAllocator1> & lhs, const ::plusgo_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plusgo_msgs::Objects_<ContainerAllocator1> & lhs, const ::plusgo_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plusgo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::Objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plusgo_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a6120d4df241a7f1dc2a96922ad41dc";
  }

  static const char* value(const ::plusgo_msgs::Objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a6120d4df241a7fULL;
  static const uint64_t static_value2 = 0x1dc2a96922ad41dcULL;
};

template<class ContainerAllocator>
struct DataType< ::plusgo_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plusgo_msgs/Objects";
  }

  static const char* value(const ::plusgo_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plusgo_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Object[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: plusgo_msgs/Object\n"
"std_msgs/Header header\n"
"uint8  source\n"
"float32 exist_confidence\n"
"\n"
"# \"UNKNOWN\",\"CONE\",\"PED\",\"BIC\",\"CAR\",\"TRUCK_BUS\",\"ULTRA_VEHICLE\"\n"
"int64  type\n"
"float32 type_confidence\n"
"int64  track_id\n"
"float32 tracking_time\n"
"\n"
"int64  motion_state\n"
"\n"
"geometry_msgs/Point32 anchor\n"
"\n"
"# the yaw angle, theta = 0.0 <=> direction = (1, 0, 0)\n"
"float32 theta\n"
"\n"
"# the main direction is the bbox length orientation\n"
"geometry_msgs/Vector3 direction\n"
"geometry_msgs/Vector3 direction_cov\n"
"geometry_msgs/Point32  center\n"
"geometry_msgs/Point32  center_cov\n"
"\n"
"# size of the oriented boundingbox, length is the size in the main direction\n"
"geometry_msgs/Vector3 size\n"
"geometry_msgs/Vector3 size_cov\n"
"\n"
"bool is_absolute_position\n"
"\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 velocity_cov\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 acceleration_cov\n"
"\n"
"float32 angle_velocity\n"
"float32 angle_velocity_cov\n"
"float32 angle_acceleration\n"
"float32 angle_acceleration_cov\n"
"\n"
"geometry_msgs/Point32[]  trajectory\n"
"geometry_msgs/Point32[]  history_type\n"
"geometry_msgs/Vector3[]  history_velocity\n"
"\n"
"Polygon    polygon\n"
"ImageRect  rect\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: plusgo_msgs/Polygon\n"
"float32 min_height\n"
"float32 max_height\n"
"geometry_msgs/Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: plusgo_msgs/ImageRect\n"
"string  image_frame\n"
"int32   x\n"
"int32   y\n"
"int32   x_\n"
"int32   y_\n"
"int32   width\n"
"int32   height\n"
"float32 angle\n"
;
  }

  static const char* value(const ::plusgo_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plusgo_msgs::Objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plusgo_msgs::Objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plusgo_msgs::Objects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plusgo_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUSGO_MSGS_MESSAGE_OBJECTS_H
