// Generated by gencpp from file plusgo_msgs/Polygon.msg
// DO NOT EDIT!


#ifndef PLUSGO_MSGS_MESSAGE_POLYGON_H
#define PLUSGO_MSGS_MESSAGE_POLYGON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace plusgo_msgs
{
template <class ContainerAllocator>
struct Polygon_
{
  typedef Polygon_<ContainerAllocator> Type;

  Polygon_()
    : min_height(0.0)
    , max_height(0.0)
    , points()  {
    }
  Polygon_(const ContainerAllocator& _alloc)
    : min_height(0.0)
    , max_height(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef float _min_height_type;
  _min_height_type min_height;

   typedef float _max_height_type;
  _max_height_type max_height;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::plusgo_msgs::Polygon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plusgo_msgs::Polygon_<ContainerAllocator> const> ConstPtr;

}; // struct Polygon_

typedef ::plusgo_msgs::Polygon_<std::allocator<void> > Polygon;

typedef boost::shared_ptr< ::plusgo_msgs::Polygon > PolygonPtr;
typedef boost::shared_ptr< ::plusgo_msgs::Polygon const> PolygonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plusgo_msgs::Polygon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plusgo_msgs::Polygon_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plusgo_msgs::Polygon_<ContainerAllocator1> & lhs, const ::plusgo_msgs::Polygon_<ContainerAllocator2> & rhs)
{
  return lhs.min_height == rhs.min_height &&
    lhs.max_height == rhs.max_height &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plusgo_msgs::Polygon_<ContainerAllocator1> & lhs, const ::plusgo_msgs::Polygon_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plusgo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::Polygon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plusgo_msgs::Polygon_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::Polygon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plusgo_msgs::Polygon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::Polygon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plusgo_msgs::Polygon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plusgo_msgs::Polygon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6917ea739af953ab09877cf096265dc0";
  }

  static const char* value(const ::plusgo_msgs::Polygon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6917ea739af953abULL;
  static const uint64_t static_value2 = 0x09877cf096265dc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::plusgo_msgs::Polygon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plusgo_msgs/Polygon";
  }

  static const char* value(const ::plusgo_msgs::Polygon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plusgo_msgs::Polygon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min_height\n"
"float32 max_height\n"
"geometry_msgs/Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::plusgo_msgs::Polygon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plusgo_msgs::Polygon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_height);
      stream.next(m.max_height);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Polygon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plusgo_msgs::Polygon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plusgo_msgs::Polygon_<ContainerAllocator>& v)
  {
    s << indent << "min_height: ";
    Printer<float>::stream(s, indent + "  ", v.min_height);
    s << indent << "max_height: ";
    Printer<float>::stream(s, indent + "  ", v.max_height);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUSGO_MSGS_MESSAGE_POLYGON_H
