(cl:in-package ros_interface-msg)
(cl:export '(ID-VAL
          ID
          CENTER_POS_VEHICLE-VAL
          CENTER_POS_VEHICLE
          CENTER_POS_ABS-VAL
          CENTER_POS_ABS
          POINTS_VEHICLE-VAL
          POINTS_VEHICLE
          POINTS_ABS-VAL
          POINTS_ABS
          THETA_VEHICLE-VAL
          THETA_VEHICLE
          THETA_ABS-VAL
          THETA_ABS
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          TYPE-VAL
          TYPE
          CONFIDENCE-VAL
          CONFIDENCE
          CONFIDENCE_TYPE-VAL
          CONFIDENCE_TYPE
          SUB_TYPE-VAL
          SUB_TYPE
          CIPV_FLAG-VAL
          CIPV_FLAG
))