(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRIVING_MODE-VAL
          DRIVING_MODE
          GEAR_LOCATION-VAL
          GEAR_LOCATION
          STEERING_VALUE-VAL
          STEERING_VALUE
          ACCEL_VALUE-VAL
          ACCEL_VALUE
          BRAKE_VALUE-VAL
          BRAKE_VALUE
          SPEED_MPS-VAL
          SPEED_MPS
          POSITION-VAL
          POSITION
          UTM_POSITION-VAL
          UTM_POSITION
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING-VAL
          HEADING
          RTK_FLAG-VAL
          RTK_FLAG
          ORIGIN_LAT-VAL
          ORIGIN_LAT
          ORIGIN_LON-VAL
          ORIGIN_LON
          CURRENT_INS_YAW-VAL
          CURRENT_INS_YAW
          AUTO_SAFE-VAL
          AUTO_SAFE
))