// Generated by gencpp from file geely_location_msgs/Geely_Location.msg
// DO NOT EDIT!


#ifndef GEELY_LOCATION_MSGS_MESSAGE_GEELY_LOCATION_H
#define GEELY_LOCATION_MSGS_MESSAGE_GEELY_LOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace geely_location_msgs
{
template <class ContainerAllocator>
struct Geely_Location_
{
  typedef Geely_Location_<ContainerAllocator> Type;

  Geely_Location_()
    : time(0.0)
    , header()
    , position()
    , pitch(0.0)
    , roll(0.0)
    , heading(0.0)
    , linear_velocity()
    , linear_acceleration()
    , angular_velocity()
    , rtk_flag(0)
    , odom_type(0)
    , auxiliary_type(0)
    , location_valid_flag(0)
    , origin_lat(0.0)
    , origin_lon(0.0)
    , utm_position()
    , change_origin_flag(0)
    , utm_position_next()
    , position_std_dev()
    , orientation_std_dev()
    , linear_velocity_std_dev()
    , linear_acceleration_std_dev()
    , angular_velocity_std_dev()  {
    }
  Geely_Location_(const ContainerAllocator& _alloc)
    : time(0.0)
    , header(_alloc)
    , position(_alloc)
    , pitch(0.0)
    , roll(0.0)
    , heading(0.0)
    , linear_velocity(_alloc)
    , linear_acceleration(_alloc)
    , angular_velocity(_alloc)
    , rtk_flag(0)
    , odom_type(0)
    , auxiliary_type(0)
    , location_valid_flag(0)
    , origin_lat(0.0)
    , origin_lon(0.0)
    , utm_position(_alloc)
    , change_origin_flag(0)
    , utm_position_next(_alloc)
    , position_std_dev(_alloc)
    , orientation_std_dev(_alloc)
    , linear_velocity_std_dev(_alloc)
    , linear_acceleration_std_dev(_alloc)
    , angular_velocity_std_dev(_alloc)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _heading_type;
  _heading_type heading;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef int32_t _rtk_flag_type;
  _rtk_flag_type rtk_flag;

   typedef int32_t _odom_type_type;
  _odom_type_type odom_type;

   typedef int32_t _auxiliary_type_type;
  _auxiliary_type_type auxiliary_type;

   typedef int32_t _location_valid_flag_type;
  _location_valid_flag_type location_valid_flag;

   typedef double _origin_lat_type;
  _origin_lat_type origin_lat;

   typedef double _origin_lon_type;
  _origin_lon_type origin_lon;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _utm_position_type;
  _utm_position_type utm_position;

   typedef int32_t _change_origin_flag_type;
  _change_origin_flag_type change_origin_flag;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _utm_position_next_type;
  _utm_position_next_type utm_position_next;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_std_dev_type;
  _position_std_dev_type position_std_dev;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _orientation_std_dev_type;
  _orientation_std_dev_type orientation_std_dev;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_velocity_std_dev_type;
  _linear_velocity_std_dev_type linear_velocity_std_dev;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_std_dev_type;
  _linear_acceleration_std_dev_type linear_acceleration_std_dev;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_std_dev_type;
  _angular_velocity_std_dev_type angular_velocity_std_dev;





  typedef boost::shared_ptr< ::geely_location_msgs::Geely_Location_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geely_location_msgs::Geely_Location_<ContainerAllocator> const> ConstPtr;

}; // struct Geely_Location_

typedef ::geely_location_msgs::Geely_Location_<std::allocator<void> > Geely_Location;

typedef boost::shared_ptr< ::geely_location_msgs::Geely_Location > Geely_LocationPtr;
typedef boost::shared_ptr< ::geely_location_msgs::Geely_Location const> Geely_LocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geely_location_msgs::Geely_Location_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::geely_location_msgs::Geely_Location_<ContainerAllocator1> & lhs, const ::geely_location_msgs::Geely_Location_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.heading == rhs.heading &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.rtk_flag == rhs.rtk_flag &&
    lhs.odom_type == rhs.odom_type &&
    lhs.auxiliary_type == rhs.auxiliary_type &&
    lhs.location_valid_flag == rhs.location_valid_flag &&
    lhs.origin_lat == rhs.origin_lat &&
    lhs.origin_lon == rhs.origin_lon &&
    lhs.utm_position == rhs.utm_position &&
    lhs.change_origin_flag == rhs.change_origin_flag &&
    lhs.utm_position_next == rhs.utm_position_next &&
    lhs.position_std_dev == rhs.position_std_dev &&
    lhs.orientation_std_dev == rhs.orientation_std_dev &&
    lhs.linear_velocity_std_dev == rhs.linear_velocity_std_dev &&
    lhs.linear_acceleration_std_dev == rhs.linear_acceleration_std_dev &&
    lhs.angular_velocity_std_dev == rhs.angular_velocity_std_dev;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::geely_location_msgs::Geely_Location_<ContainerAllocator1> & lhs, const ::geely_location_msgs::Geely_Location_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace geely_location_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geely_location_msgs::Geely_Location_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geely_location_msgs::Geely_Location_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geely_location_msgs::Geely_Location_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87793f2358c4810e566e37606b1cc817";
  }

  static const char* value(const ::geely_location_msgs::Geely_Location_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87793f2358c4810eULL;
  static const uint64_t static_value2 = 0x566e37606b1cc817ULL;
};

template<class ContainerAllocator>
struct DataType< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geely_location_msgs/Geely_Location";
  }

  static const char* value(const ::geely_location_msgs::Geely_Location_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Geely_Location.msg\n"
"# /localization/global_fusion/Location/tju 对应的消息类型\n"
"\n"
"# 时间戳\n"
"float64 time\n"
"\n"
"# 标准 ROS 头\n"
"std_msgs/Header header\n"
"\n"
"# 原始经纬高\n"
"# 约定：x=lon, y=lat, z=height（仅占位，不影响UTM使用）\n"
"geometry_msgs/Point position\n"
"\n"
"# 姿态（弧度）\n"
"float64 pitch\n"
"float64 roll\n"
"float64 heading\n"
"\n"
"# ENU 速度/加速度/角速度（单位：m/s, m/s^2, rad/s）\n"
"geometry_msgs/Vector3 linear_velocity\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"geometry_msgs/Vector3 angular_velocity\n"
"\n"
"# 状态标志\n"
"int32 rtk_flag\n"
"int32 odom_type\n"
"int32 auxiliary_type\n"
"int32 location_valid_flag\n"
"\n"
"# 原点信息\n"
"float64 origin_lat\n"
"float64 origin_lon\n"
"\n"
"# UTM 位置（m）：x=East, y=North, z=Up\n"
"geometry_msgs/Point utm_position\n"
"\n"
"# 原点切换标记与下一帧UTM\n"
"int32 change_origin_flag\n"
"geometry_msgs/Point utm_position_next\n"
"\n"
"# 各类标准差（Vector3）\n"
"geometry_msgs/Vector3 position_std_dev\n"
"geometry_msgs/Vector3 orientation_std_dev\n"
"geometry_msgs/Vector3 linear_velocity_std_dev\n"
"geometry_msgs/Vector3 linear_acceleration_std_dev\n"
"geometry_msgs/Vector3 angular_velocity_std_dev\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::geely_location_msgs::Geely_Location_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.heading);
      stream.next(m.linear_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.angular_velocity);
      stream.next(m.rtk_flag);
      stream.next(m.odom_type);
      stream.next(m.auxiliary_type);
      stream.next(m.location_valid_flag);
      stream.next(m.origin_lat);
      stream.next(m.origin_lon);
      stream.next(m.utm_position);
      stream.next(m.change_origin_flag);
      stream.next(m.utm_position_next);
      stream.next(m.position_std_dev);
      stream.next(m.orientation_std_dev);
      stream.next(m.linear_velocity_std_dev);
      stream.next(m.linear_acceleration_std_dev);
      stream.next(m.angular_velocity_std_dev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Geely_Location_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geely_location_msgs::Geely_Location_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geely_location_msgs::Geely_Location_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "linear_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "rtk_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rtk_flag);
    s << indent << "odom_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.odom_type);
    s << indent << "auxiliary_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.auxiliary_type);
    s << indent << "location_valid_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.location_valid_flag);
    s << indent << "origin_lat: ";
    Printer<double>::stream(s, indent + "  ", v.origin_lat);
    s << indent << "origin_lon: ";
    Printer<double>::stream(s, indent + "  ", v.origin_lon);
    s << indent << "utm_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.utm_position);
    s << indent << "change_origin_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.change_origin_flag);
    s << indent << "utm_position_next: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.utm_position_next);
    s << indent << "position_std_dev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position_std_dev);
    s << indent << "orientation_std_dev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation_std_dev);
    s << indent << "linear_velocity_std_dev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity_std_dev);
    s << indent << "linear_acceleration_std_dev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration_std_dev);
    s << indent << "angular_velocity_std_dev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity_std_dev);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEELY_LOCATION_MSGS_MESSAGE_GEELY_LOCATION_H
