# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rl_planning/PlanningPath.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PlanningPath(genpy.Message):
  _md5sum = "442a1e70c87c57dd2f625de9cdf24bc4"
  _type = "rl_planning/PlanningPath"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64[500] fx
float64[500] fy
float64[500] v
float64[500] a
float64[500] theta
float64[500] kappa
float64[500] s
int32 collision_risk
float64 SRQ_value

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','fx','fy','v','a','theta','kappa','s','collision_risk','SRQ_value']
  _slot_types = ['std_msgs/Header','float64[500]','float64[500]','float64[500]','float64[500]','float64[500]','float64[500]','float64[500]','int32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,fx,fy,v,a,theta,kappa,s,collision_risk,SRQ_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanningPath, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.fx is None:
        self.fx = [0.] * 500
      if self.fy is None:
        self.fy = [0.] * 500
      if self.v is None:
        self.v = [0.] * 500
      if self.a is None:
        self.a = [0.] * 500
      if self.theta is None:
        self.theta = [0.] * 500
      if self.kappa is None:
        self.kappa = [0.] * 500
      if self.s is None:
        self.s = [0.] * 500
      if self.collision_risk is None:
        self.collision_risk = 0
      if self.SRQ_value is None:
        self.SRQ_value = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.fx = [0.] * 500
      self.fy = [0.] * 500
      self.v = [0.] * 500
      self.a = [0.] * 500
      self.theta = [0.] * 500
      self.kappa = [0.] * 500
      self.s = [0.] * 500
      self.collision_risk = 0
      self.SRQ_value = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_500d().pack(*self.fx))
      buff.write(_get_struct_500d().pack(*self.fy))
      buff.write(_get_struct_500d().pack(*self.v))
      buff.write(_get_struct_500d().pack(*self.a))
      buff.write(_get_struct_500d().pack(*self.theta))
      buff.write(_get_struct_500d().pack(*self.kappa))
      buff.write(_get_struct_500d().pack(*self.s))
      _x = self
      buff.write(_get_struct_id().pack(_x.collision_risk, _x.SRQ_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4000
      self.fx = _get_struct_500d().unpack(str[start:end])
      start = end
      end += 4000
      self.fy = _get_struct_500d().unpack(str[start:end])
      start = end
      end += 4000
      self.v = _get_struct_500d().unpack(str[start:end])
      start = end
      end += 4000
      self.a = _get_struct_500d().unpack(str[start:end])
      start = end
      end += 4000
      self.theta = _get_struct_500d().unpack(str[start:end])
      start = end
      end += 4000
      self.kappa = _get_struct_500d().unpack(str[start:end])
      start = end
      end += 4000
      self.s = _get_struct_500d().unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.collision_risk, _x.SRQ_value,) = _get_struct_id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.fx.tostring())
      buff.write(self.fy.tostring())
      buff.write(self.v.tostring())
      buff.write(self.a.tostring())
      buff.write(self.theta.tostring())
      buff.write(self.kappa.tostring())
      buff.write(self.s.tostring())
      _x = self
      buff.write(_get_struct_id().pack(_x.collision_risk, _x.SRQ_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4000
      self.fx = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      start = end
      end += 4000
      self.fy = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      start = end
      end += 4000
      self.v = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      start = end
      end += 4000
      self.a = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      start = end
      end += 4000
      self.theta = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      start = end
      end += 4000
      self.kappa = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      start = end
      end += 4000
      self.s = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=500)
      _x = self
      start = end
      end += 12
      (_x.collision_risk, _x.SRQ_value,) = _get_struct_id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_500d = None
def _get_struct_500d():
    global _struct_500d
    if _struct_500d is None:
        _struct_500d = struct.Struct("<500d")
    return _struct_500d
_struct_id = None
def _get_struct_id():
    global _struct_id
    if _struct_id is None:
        _struct_id = struct.Struct("<id")
    return _struct_id
