# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rl_planning/VehicleInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import rl_planning.msg
import std_msgs.msg

class VehicleInfo(genpy.Message):
  _md5sum = "2080f30d52a247820d94f7875c4574f1"
  _type = "rl_planning/VehicleInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 id
string label
geometry_msgs/PolygonStamped convex_hull
float64 length
float64 width
float64 height
Point actor_pos
Point actor_rel_pos
Vector3D actor_vel
Vector3D actor_rel_vel
Vector3D actor_acc
float64 actor_psi
float64 actor_speed

================================================================================
MSG: geometry_msgs/PolygonStamped
# This represents a Polygon with reference coordinate frame and timestamp
Header header
Polygon polygon

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: rl_planning/Point
float64 x 
float64 y 
float64 z 

================================================================================
MSG: rl_planning/Vector3D
float64 x
float64 y
float64 z
"""
  __slots__ = ['id','label','convex_hull','length','width','height','actor_pos','actor_rel_pos','actor_vel','actor_rel_vel','actor_acc','actor_psi','actor_speed']
  _slot_types = ['uint32','string','geometry_msgs/PolygonStamped','float64','float64','float64','rl_planning/Point','rl_planning/Point','rl_planning/Vector3D','rl_planning/Vector3D','rl_planning/Vector3D','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,label,convex_hull,length,width,height,actor_pos,actor_rel_pos,actor_vel,actor_rel_vel,actor_acc,actor_psi,actor_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.label is None:
        self.label = ''
      if self.convex_hull is None:
        self.convex_hull = geometry_msgs.msg.PolygonStamped()
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.actor_pos is None:
        self.actor_pos = rl_planning.msg.Point()
      if self.actor_rel_pos is None:
        self.actor_rel_pos = rl_planning.msg.Point()
      if self.actor_vel is None:
        self.actor_vel = rl_planning.msg.Vector3D()
      if self.actor_rel_vel is None:
        self.actor_rel_vel = rl_planning.msg.Vector3D()
      if self.actor_acc is None:
        self.actor_acc = rl_planning.msg.Vector3D()
      if self.actor_psi is None:
        self.actor_psi = 0.
      if self.actor_speed is None:
        self.actor_speed = 0.
    else:
      self.id = 0
      self.label = ''
      self.convex_hull = geometry_msgs.msg.PolygonStamped()
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.actor_pos = rl_planning.msg.Point()
      self.actor_rel_pos = rl_planning.msg.Point()
      self.actor_vel = rl_planning.msg.Vector3D()
      self.actor_rel_vel = rl_planning.msg.Vector3D()
      self.actor_acc = rl_planning.msg.Vector3D()
      self.actor_psi = 0.
      self.actor_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      buff.write(_get_struct_I().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.convex_hull.header.seq, _x.convex_hull.header.stamp.secs, _x.convex_hull.header.stamp.nsecs))
      _x = self.convex_hull.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.convex_hull.polygon.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.convex_hull.polygon.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_20d().pack(_x.length, _x.width, _x.height, _x.actor_pos.x, _x.actor_pos.y, _x.actor_pos.z, _x.actor_rel_pos.x, _x.actor_rel_pos.y, _x.actor_rel_pos.z, _x.actor_vel.x, _x.actor_vel.y, _x.actor_vel.z, _x.actor_rel_vel.x, _x.actor_rel_vel.y, _x.actor_rel_vel.z, _x.actor_acc.x, _x.actor_acc.y, _x.actor_acc.z, _x.actor_psi, _x.actor_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.convex_hull is None:
        self.convex_hull = geometry_msgs.msg.PolygonStamped()
      if self.actor_pos is None:
        self.actor_pos = rl_planning.msg.Point()
      if self.actor_rel_pos is None:
        self.actor_rel_pos = rl_planning.msg.Point()
      if self.actor_vel is None:
        self.actor_vel = rl_planning.msg.Vector3D()
      if self.actor_rel_vel is None:
        self.actor_rel_vel = rl_planning.msg.Vector3D()
      if self.actor_acc is None:
        self.actor_acc = rl_planning.msg.Vector3D()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.convex_hull.header.seq, _x.convex_hull.header.stamp.secs, _x.convex_hull.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.convex_hull.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.convex_hull.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.convex_hull.polygon.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.convex_hull.polygon.points.append(val1)
      _x = self
      start = end
      end += 160
      (_x.length, _x.width, _x.height, _x.actor_pos.x, _x.actor_pos.y, _x.actor_pos.z, _x.actor_rel_pos.x, _x.actor_rel_pos.y, _x.actor_rel_pos.z, _x.actor_vel.x, _x.actor_vel.y, _x.actor_vel.z, _x.actor_rel_vel.x, _x.actor_rel_vel.y, _x.actor_rel_vel.z, _x.actor_acc.x, _x.actor_acc.y, _x.actor_acc.z, _x.actor_psi, _x.actor_speed,) = _get_struct_20d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      buff.write(_get_struct_I().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.convex_hull.header.seq, _x.convex_hull.header.stamp.secs, _x.convex_hull.header.stamp.nsecs))
      _x = self.convex_hull.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.convex_hull.polygon.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.convex_hull.polygon.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_20d().pack(_x.length, _x.width, _x.height, _x.actor_pos.x, _x.actor_pos.y, _x.actor_pos.z, _x.actor_rel_pos.x, _x.actor_rel_pos.y, _x.actor_rel_pos.z, _x.actor_vel.x, _x.actor_vel.y, _x.actor_vel.z, _x.actor_rel_vel.x, _x.actor_rel_vel.y, _x.actor_rel_vel.z, _x.actor_acc.x, _x.actor_acc.y, _x.actor_acc.z, _x.actor_psi, _x.actor_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.convex_hull is None:
        self.convex_hull = geometry_msgs.msg.PolygonStamped()
      if self.actor_pos is None:
        self.actor_pos = rl_planning.msg.Point()
      if self.actor_rel_pos is None:
        self.actor_rel_pos = rl_planning.msg.Point()
      if self.actor_vel is None:
        self.actor_vel = rl_planning.msg.Vector3D()
      if self.actor_rel_vel is None:
        self.actor_rel_vel = rl_planning.msg.Vector3D()
      if self.actor_acc is None:
        self.actor_acc = rl_planning.msg.Vector3D()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.convex_hull.header.seq, _x.convex_hull.header.stamp.secs, _x.convex_hull.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.convex_hull.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.convex_hull.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.convex_hull.polygon.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.convex_hull.polygon.points.append(val1)
      _x = self
      start = end
      end += 160
      (_x.length, _x.width, _x.height, _x.actor_pos.x, _x.actor_pos.y, _x.actor_pos.z, _x.actor_rel_pos.x, _x.actor_rel_pos.y, _x.actor_rel_pos.z, _x.actor_vel.x, _x.actor_vel.y, _x.actor_vel.z, _x.actor_rel_vel.x, _x.actor_rel_vel.y, _x.actor_rel_vel.z, _x.actor_acc.x, _x.actor_acc.y, _x.actor_acc.z, _x.actor_psi, _x.actor_speed,) = _get_struct_20d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_20d = None
def _get_struct_20d():
    global _struct_20d
    if _struct_20d is None:
        _struct_20d = struct.Struct("<20d")
    return _struct_20d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
